### ISSUE TITLE
rev F cap mod against hall digital noise [focus on C3 the one shared with VR][two modded boards in PR]

### ISSUE THREAD

**Issue by rusefillc** [rusefi/alphax-4chan#102]
How do we hand modify add caps for hall digital noise drama?

https://github.com/rusefi/alphax-4chan/issues/72

pins C3 and C7

actually it's mostly C3 which has issue. Is it same VR cap or different cap to improve mostly C3 digital hall input?

![image](https://user-images.githubusercontent.com/48498823/220509740-b7548fcd-f3b7-4660-840e-07e24b3125c6.png)

**Comment by ElDominio** [comment]
Question, does changing to E5 help at all?

**Comment by rusefillc** [comment]
Question: is there a difference between C3 and C7?

**Comment by Qwerty-OFF** [comment]
C7 is traditional OpAmp input through Input module
C3 connected to VR discrete and Schmitt trigger
Try to add 1n capcitor:
![image](https://user-images.githubusercontent.com/4116383/220755071-14f3c441-0ab9-4b0a-9cef-d486cfd89683.png)
![image](https://user-images.githubusercontent.com/4116383/220756528-d098cc09-c10a-4265-8b81-b85b441e3b2b.png)
And remove this:
![image](https://user-images.githubusercontent.com/4116383/220756048-3a4df303-c2f4-43e0-b16e-8759c61a424e.png)

**Comment by rusefillc** [comment]
@timbelom please attempt two above mentioned mods on 4 chan rev E we have

* take 0805 cap marked 1n
* remove resistor as described

**Comment by rusefillc** [comment]
@Qwerty-OFF посоветуй плиз куда кидать на землю конденсатор рядом с R22 тоже картинкой?

**Comment by Qwerty-OFF** [comment]
![image](https://user-images.githubusercontent.com/4116383/221264151-de068ff4-5500-428b-a94e-756dd62803aa.png)
![image](https://user-images.githubusercontent.com/4116383/221264971-80aae374-01ff-4996-bf8b-d1aa89e35065.png)
Лучше использовать SMD

**Comment by rusefillc** [comment]
@Qwerty-OFF my bad we have rev F not rev E, need same instructions for rev F with latest VR

**Comment by rusefillc** [comment]
@Qwerty-OFF rev C does not have D57 is there a chance to fix rev C? 

overall at the moment we have rev F and rev C to modify

**Comment by rusefillc** [comment]
1nf
![image](https://user-images.githubusercontent.com/48498823/221633781-6a57677a-4f05-475c-a556-0b5751a100c3.png)

**Comment by rusefillc** [comment]
Actually @Qwerty-OFF says to remove R753 to disconnect VR just for a test

**Comment by rusefillc** [comment]
@ElDominio this board is on the way to you. Please test and share results :)

**Comment by rusefillc** [comment]
@Qwerty-OFF we have positive test results! we need this mod on rev G

https://github.com/rusefi/rusefi/issues/5211#issuecomment-1493075254

**Comment by Qwerty-OFF** [comment]
![image](https://user-images.githubusercontent.com/4116383/229368566-b239fc55-cf08-4202-b1b1-f00611bf6470.png)
