### ISSUE TITLE
Please ship some 4chan to NJ

### ISSUE THREAD

**Issue by rusefillc** [rusefi/alphax-4chan#103]
@ElDominio i will be shipping you my last rev F board, please ship at least one rev F board

overall I have only one rev C board and nada mas, please ship me any rev D and E if you have those

**Comment by rusefillc** [comment]
@ElDominio poke

**Comment by ElDominio** [comment]
9405803699300818959286

Modded 4chan
virgin 4chan

**Comment by rusefillc** [comment]
Arrived! https://github.com/rusefi/alphax-4chan/issues/106
