### ISSUE TITLE
We need to move MAP sensor to a safer spot. Maybe add space for much more got glue/epoxy around MAP

### ISSUE THREAD

**Issue by rusefillc** [rusefi/alphax-4chan#106]
* We need space for much more got glue around MAP
* can we make a couple of 2mm vias on sides of MAP for hot glue to attach to holes?

Pictured rev F with too many components around allowing only for small amount of hot glue

![WhatsApp Image 2023-03-15 at 13 44 40](https://user-images.githubusercontent.com/48498823/225397688-c962bb2b-7ef7-4e43-951e-1a5f872e07a7.jpg)

**Comment by ElDominio** [comment]
I think more glue is not the solution

Move MAP location nearer to the middle of the board or close to connector, to evade damage during shipping

![IMG-20230315-WA0012.jpg](https://user-images.githubusercontent.com/5685108/225400735-826e16c2-6b24-4376-a02a-d257ab2c8c48.jpg)

Like so
![Screenshot_20230315-135757.jpg](https://user-images.githubusercontent.com/5685108/225401029-329a16ae-a5f9-4d7a-b585-693177313db7.jpg)

**Comment by mck1117** [comment]
> I think more glue is not the solution

Besides, no amount of glue will save you. The pins/PCB are stiffer than the glue, so any deflection will result in stress in the pins, not the glue. The pins will snap off, then the glue will bear the load only once that's happened. You need either a stiff urethane glue or epoxy, mechanical connection (ie, bolt), or move the sensor.

**Comment by rusefillc** [comment]
@ElDominio says

Move MAP location nearer to the middle of the board or close to connector, to evade damage during shipping

![IMG-20230315-WA0012.jpg](https://user-images.githubusercontent.com/5685108/225400735-826e16c2-6b24-4376-a02a-d257ab2c8c48.jpg)

Like so
![Screenshot_20230315-135757.jpg](https://user-images.githubusercontent.com/5685108/225401029-329a16ae-a5f9-4d7a-b585-693177313db7.jpg)

**Comment by rusefillc** [comment]
> move the sensor.

I agree, location on the edge seems to be the main issue

**Comment by Qwerty-OFF** [comment]
![image](https://user-images.githubusercontent.com/4116383/229364983-bb99b02a-501d-40cd-b4aa-768193bd3855.png)

**Comment by rusefillc** [comment]
@Qwerty-OFF still on the edge :(

**Comment by rusefillc** [comment]
@Qwerty-OFF can we move to 

![image](https://user-images.githubusercontent.com/48498823/229365144-5c7cfe08-c692-4471-a594-801bf216cf38.png)

so that it's NOT on the edge of the board?

**Comment by Qwerty-OFF** [comment]
![Uploading image.png…]()
