### ISSUE TITLE
ETB another idea - crazy capacitor flexibility

### ISSUE THREAD

**Issue by rusefillc** [rusefi/alphax-4chan#110]
Do we have space for electrolytic capacitor?

End goal is be able to hand modify board into test configuration to be much closer to MRE/proteus.

**Comment by Qwerty-OFF** [comment]
![image](https://user-images.githubusercontent.com/4116383/226140757-73ac5e1c-11ea-40a4-bc54-48f9d95209b3.png)

![image](https://user-images.githubusercontent.com/4116383/226140748-1ee98d11-ab75-4b8a-af45-ae3ac48d19f2.png)

**Comment by andreika-git** [comment]
Are we sure that the pcb file is updated with the new cap?
![зображення](https://user-images.githubusercontent.com/15104768/227030366-0b2acd07-195e-49ee-a9cb-3c897fcdd992.png)

**Comment by Qwerty-OFF** [comment]
![image](https://user-images.githubusercontent.com/4116383/229304660-89464d5f-bf82-479b-bb9c-d1389985cc50.png)
