### ISSUE TITLE
Suspect VR threshold is affecting ALL kinds of timing

### ISSUE THREAD

**Issue by ElDominio** [rusefi/alphax-4chan#115]
I have a car on the dyno with this curve on the VR threshold
![image](https://user-images.githubusercontent.com/5685108/229182249-77921f99-e7d7-44d8-94ae-690bbfebda10.png)

If I change to this:
![image](https://user-images.githubusercontent.com/5685108/229182313-02052e90-6277-42c1-b35c-6510c4fa058c.png)

The powerband loses power all across the board (in the tune of 3hp on a 100hp car)

This leads me to believe VR threshold settings affect timing.

**Comment by mck1117** [comment]
does this board have the added caps to the vr module?

**Comment by ElDominio** [comment]
Does not

**Comment by mck1117** [comment]
Then this is expected. You need the caps.

**Comment by ElDominio** [comment]
Good to know heh thanks

**Comment by rusefillc** [comment]
https://github.com/rusefi/rusefi/wiki/AlphaX-4chan#changelog says rev F has VR fix
