### ISSUE TITLE
4g experiments without touching VR pins

### ISSUE THREAD

**Issue by rusefillc** [rusefi/alphax-4chan#121]
We shall try to run 4g on rev F and rev G while NOT using C2,C3,E5,E6

meaning that we have C7 E3 E4

**Comment by rusefillc** [comment]
@Qwerty-OFF E3 and E4 are they hall-compatible on either F or G?

**Comment by rusefillc** [comment]
E3 and E4 have 100nF caps which would need to be removed or better changed to 1-10nF

**Comment by ElDominio** [comment]
I have confirmed a simple fix on revC and revE

On revC, I did the same as was said by @Qwerty-OFF , adding 1nf caps to IN_CRANK and a 4.6k resistor to R7 jumper hole to R40 pad (removing R44 in the process)
![image](https://user-images.githubusercontent.com/5685108/232250153-1dd1834d-f15e-48c3-9ee5-6303d4ce8bb7.png)

still revC, added 1nf caps to IN_CRANK as shown here
![image](https://user-images.githubusercontent.com/5685108/232250202-10008ca4-450e-411f-9fad-2ea0e6165561.png)

and to D57 (on revF schematic) pad on R24
![image](https://user-images.githubusercontent.com/5685108/232250235-511e267d-351e-4961-81da-ec0e0e1d98a3.png)

This allowed me to read RPM perfectly on 4G93 on a revC
![image](https://user-images.githubusercontent.com/5685108/232250255-2e9c7a92-9db5-477c-8581-4fa0d529edbc.png)

**Comment by ElDominio** [comment]
On revE, I **_ONLY_** added a 1nf cap from bottom pad of R24 to ground
![image](https://user-images.githubusercontent.com/5685108/232250309-754044a0-adf2-490b-9e54-978df87f2326.png)

And also reads perfectly
[perfect4reading4gonlyonecap.zip](https://github.com/rusefi/alphax-4chan/files/11240484/perfect4reading4gonlyonecap.zip)

This revE has stock R44 resistor, no resistors removed to disable VR, no external resistors, and no cap on IN_CRANK. Still works great.
![image](https://user-images.githubusercontent.com/5685108/232250368-25beb3e6-9ecf-4325-bb5c-8d4ac7c6b0a6.png)

**Comment by ElDominio** [comment]
Fun fact: revE with 1nf cap ALSO works on VR car, specifically 24-1 cam speed Honda B20, with settings from unmodified ECU.
