### ISSUE TITLE
test rev G Hall test default configuration with two resistors removed board number 0 C3+C4

### ISSUE THREAD

**Issue by rusefillc** [rusefi/alphax-4chan#124]
@ElDominio please confirm that you have a working heat gun
@ElDominio please do not use soldering iron to remove R4
@ElDominio please remove R4 using hot air and tweezers from back side. please place R4 into a little bag mark "R4"
@ElDominio please remove R23 not too far from R4. please place R23 into a little bag mark "R23"

![image](https://user-images.githubusercontent.com/48498823/233429692-44eeb178-0082-480b-9ff1-0690dd334971.png)

![image](https://user-images.githubusercontent.com/48498823/233430158-1562743a-2250-4eca-b67a-7d0a01b186d2.png)

capacitors stay default
![image](https://user-images.githubusercontent.com/48498823/233428349-594d8536-48f5-4352-a18f-921a92e06480.png)

@ElDominio need to run this board as hall on C3+C4

**Comment by ElDominio** [comment]
Use C3 for CKP and C4 for CMP??

**Comment by rusefillc** [comment]
@ElDominio yes that the request from what I see

**Comment by rusefillc** [comment]
@ElDominio please provide a status update for this C3+C4

**Comment by ElDominio** [comment]
C3+C4 works fine on easy Hall car Lancer with 4B11, tested on all boards.

Not tested on problematic hall 4G93 with split cam+crank

**Comment by ElDominio** [comment]
Tried revving on board0 and board2, both worked fine @rusefillc

**Comment by ElDominio** [comment]
RevG works with Hall/VR
