### ISSUE TITLE
test rev G test VR configuration with two resistors removed board number 0, also boards 1 and 2

### ISSUE THREAD

**Issue by rusefillc** [rusefi/alphax-4chan#126]
Same physical unit as https://github.com/rusefi/alphax-4chan/issues/124

@ElDominio need to run this board as VR C2+C3

**Comment by rusefillc** [comment]
board 1 has C17 removed

![image](https://user-images.githubusercontent.com/48498823/233439520-0b724c46-7b6d-4288-abf3-8f497325c662.png)

**Comment by rusefillc** [comment]
board 2 has C20 added over default
![image](https://user-images.githubusercontent.com/48498823/233439839-ce453430-ee51-4d3f-9dbf-1e258b406225.png)

**Comment by ElDominio** [comment]
https://rusefi.com/online/view.php?log=1228

With resistors removed reads VR, without removing them, it did not read. Log is with resistors removed.

This car has run on revB/revC/revD so it seems to be a happy simple VR, pends testing on a car with more annoying VR

**Comment by rusefillc** [comment]
@ElDominio 
* fact 1: any rev board is useless in the as-soldered-on-factory resistor configuration
* fact 2: as of now I have not removed any resistor from any of the five rev G boards in existence
* conclusion: @ElDominio to remove R from any test board for any test

**Comment by ElDominio** [comment]
board 2 log, r4 and r23 removed:
[revGtestVRver2.zip](https://github.com/rusefi/alphax-4chan/files/11347674/revGtestVRver2.zip)

board 1 log, r4 and r23 removed:
[revGtestVRver1.zip](https://github.com/rusefi/alphax-4chan/files/11347711/revGtestVRver1.zip)

board 0 log, r4 and r23 removed: 
[revGtestVRver0.zip](https://github.com/rusefi/alphax-4chan/files/11347787/revGtestVRver0.zip)


all tests done on Toyota 1NZ 36-2 Crank, 4-1 cam, dual VR
tune file
[tuneforyaris.zip](https://github.com/rusefi/alphax-4chan/files/11347805/tuneforyaris.zip)

**Comment by rusefillc** [comment]
@ElDominio tl,dr?

**Comment by ElDominio** [comment]
all broken, can see sync failure on log

**Comment by ElDominio** [comment]
This was tested on problematic VR from Toyota Yaris 1NZ

All boards could not rev past idle due to sync issues, the car works much better on revF

Easy VR from Honda B20 work fine on board 0

**Comment by Qwerty-OFF** [comment]
Please remove R22, R35, R1126, R1135 on board 1 (without C17, C20) and check VR C2+C3 again

**Comment by rusefillc** [comment]
@ElDominio https://rusefi.com/docs/ibom/alphax_4ch-g-ibom.html

**Comment by ElDominio** [comment]
I think it is worse now
[moddedwithoutalotofresistorsboardv1revG.zip](https://github.com/rusefi/alphax-4chan/files/11360218/moddedwithoutalotofresistorsboardv1revG.zip)

**Comment by rusefillc** [comment]
@ElDominio please add a photo with all mods?

**Comment by ElDominio** [comment]
![IMG_20230429_192301.jpg](https://user-im![IMG_20230429_192246.jpg](https://user-images.githubusercontent.com/5685108/235328016-7b7e313f-827b-44f8-8b67-7aba5a1a3cf5.jpg)

17-02864297-7550-47fe-8a32-603438daf84f.jpg)

![Uploading IMG_20230429_192246.jpg …]()

**Comment by rusefillc** [comment]
![WhatsApp Image 2023-04-29 at 19 31 39 2](https://user-images.githubusercontent.com/48498823/235328240-6a4a2cfd-4914-4e17-a658-e999db5c9141.jpg)
![WhatsApp Image 2023-04-29 at 19 31 39](https://user-images.githubusercontent.com/48498823/235328241-f1029062-68da-4c01-9476-e87bba99be7c.jpg)

**Comment by ElDominio** [comment]
Can this and revG tickets be closed yet? I don't see why not?
