### ISSUE TITLE
rev A: CAN sleep/wake is sporadic

### ISSUE THREAD

**Issue by rusefillc** [rusefi/alphax-4chan#13]
4chan with 4 wires:
GND, +12, CAN_H, CAN_L

CanHacker device "shot" single CAN sending feature

```
canRxAdd(0x570)
function onCanRx(bus, id, dlc, data)
	print('got CAN id=' ..id ..' dlc=' ..dlc)
	id11 = id % 2048
	if id11 == 0x570 then
		mcu_standby()
	end
end
```

PROBLEM:
60% of the times 4chanA goes to sleep with first 0x570 packet and wakes up on next 0x570

40% of the times 4chanA would reboot on incoming 0x570 packet

@andreika-git did you say we have something inverting something somewhere? cannot find it

![image](https://user-images.githubusercontent.com/48498823/160945687-76c4054f-e28a-4354-a3fb-8ace2535ce0d.png)

**Comment by andreika-git** [comment]
A proper (hopefully?) CAN wakeup with an additional inverted buffer is on 2ch-revC and h81hd-revA, not on 4ch-revA.

**Comment by rusefillc** [comment]
which makes me wonder how come it works at 60% :)

**Comment by rusefillc** [comment]
no time to investigate rev A configuration
