### ISSUE TITLE
VVT output F2 not working on RevG

### ISSUE THREAD

**Issue by ElDominio** [rusefi/alphax-4chan#132]
VVT seems to not work on revG, testing on Yaris

log: https://rusefi.com/online/view.php?log=1232
tune is linked to log on rusefi online

possible culprit sames as revG PPS?

**Comment by rusefillc** [comment]
rev G
![image](https://user-images.githubusercontent.com/48498823/236638891-207807d9-aab6-40f5-bbb7-782d24fb3395.png)

![image](https://user-images.githubusercontent.com/48498823/236638926-ee7891bf-2af9-41ad-81f5-8db704bb917b.png)

![image](https://user-images.githubusercontent.com/48498823/236638944-f2256047-4b92-4d9e-8edc-27233ebc3586.png)

![image](https://user-images.githubusercontent.com/48498823/236638964-a8239c6f-24fc-4f4a-986a-61932d9f0f00.png)

**Comment by rusefillc** [comment]
rev F
![image](https://user-images.githubusercontent.com/48498823/236638997-cafe6840-afda-49b5-81ac-75df851371bc.png)

**Comment by rusefillc** [comment]
@ElDominio yes VVT1 and VVT2 pinout has changed on rev G, now adding "F2 - VVT#1 rev G" and "F4 - VVT#2 rev G" pins

**Comment by ElDominio** [comment]
Is there a way to catch any other pins like these?

**Comment by rusefillc** [comment]
@ElDominio yes, just go over all pins in the schematics

**Comment by rusefillc** [comment]
Also https://rusefi.com/docs/pinouts/hellen/alphax-4chan/ progress has helped since it at least detects pin overlap.

Legacy VVT pins have funny names in latest firmware.

**Comment by ElDominio** [comment]
This seems to still be broken; did it break when removing old compatibility?

**Comment by rusefillc** [comment]
@ElDominio please clarify why closed?

**Comment by ElDominio** [comment]
Did not know if a new ticket was better, asking for processor pins.

**Comment by rusefillc** [comment]
https://github.com/rusefi/alphax-4chan/issues/159 not better

**Comment by rusefillc** [comment]
@ElDominio too many things bundled together here - random vehicle etc etc

when one suspects a hardware problem on the board we have to start by testing physical output on a bench. clicking a known good test injector using "injector bench" button seems to be the most reliable way


i have a rev G board which passes stim QC testing on both vvt and idle outputs that confirm that firmware is capable of toggling output wire

```
 * Board detected: 4chan rev index 1
                      numOutputs 8
               Setting ADDR 0
               sending line=1 value=1
                      ADC says HIGH 1@0 3.080v
               sending line=1 value=0
                      ADC says LOW 1@1 0.002v
               sending line=1 value=1
               sending line=1 value=0
0/16 A8 - Injector 1 GOOD channel 1
               Setting ADDR 1
               sending line=2 value=1
                      ADC says HIGH 2@0 3.080v
               sending line=2 value=0
                      ADC says LOW 2@1 0.002v
               sending line=2 value=1
               sending line=2 value=0
1/16 B8 - Injector 2 GOOD channel 2
               Setting ADDR 2
               sending line=3 value=1
                      ADC says HIGH 3@0 3.080v
               sending line=3 value=0
                      ADC says LOW 3@1 0.002v
               sending line=3 value=1
               sending line=3 value=0
2/16 D1 - Injector 3 GOOD channel 3
               Setting ADDR 3
               sending line=4 value=1
                      ADC says HIGH 4@0 3.080v
               sending line=4 value=0
                      ADC says LOW 4@1 0.002v
               sending line=4 value=1
               sending line=4 value=0
3/16 E1 - Injector 4 GOOD channel 4
               Setting ADDR 4
               sending line=5 value=1
                      ADC says HIGH 5@0 1.399v
               sending line=5 value=0
                      ADC says LOW 5@1 0.001v
               sending line=5 value=1
               sending line=5 value=0
4/16 F2 - VVT#1 rev G GOOD channel 5
               Setting ADDR 5
               sending line=6 value=1
                      ADC says HIGH 6@0 1.604v
               sending line=6 value=0
                      ADC says LOW 6@1 0.002v
               sending line=6 value=1
               sending line=6 value=0
5/16 F4 - VVT#2 rev G GOOD channel 6
               Setting ADDR 6
               sending line=7 value=1
                      ADC says HIGH 7@0 1.688v
               sending line=7 value=0
                      ADC says LOW 7@1 0.002v
               sending line=7 value=1
               sending line=7 value=0
6/16 F1 - Idle2 GOOD channel 7
               Setting ADDR 7
               sending line=8 value=1
                      ADC says HIGH 8@0 1.720v
               sending line=8 value=0
                      ADC says LOW 8@1 0.001v
               sending line=8 value=1
               sending line=8 value=0
7/16 C8 - Idle GOOD channel 8
```
