### ISSUE TITLE
Aux: schematics vs pcb brain pain

### ISSUE THREAD

**Issue by rusefillc** [rusefi/alphax-4chan#133]
Fact: schematics implies pinout niceness but reality does not match the dream?

![WhatsApp Image 2023-05-07 at 10 22 38](https://user-images.githubusercontent.com/48498823/236683393-6c9760e6-04a6-44fa-817c-0db4e9889548.jpg)

![image](https://user-images.githubusercontent.com/48498823/236683383-25ac9ae2-bb3a-4e34-b1da-2269d6f8574d.png)

**Comment by Qwerty-OFF** [comment]
Fixed
![image](https://github.com/rusefi/alphax-4chan/assets/4116383/05221b27-0dfe-44a3-b1e9-5a8856056d5e)
