### ISSUE TITLE
K24 cam sensor not reading

### ISSUE THREAD

**Issue by ElDominio** [rusefi/alphax-4chan#135]
I can see lights blinking for both cam inputs, but no reading on TS or log

log at https://rusefi.com/online/view.php?log=1233 tune is tied to log

All Crank/Cam are hall.
vvtchannel can be seen with data.

**Comment by rusefillc** [comment]
honda k intake is not suitable for engine sync. I've just improved the firmware to have an explicit fatal error

![image](https://github.com/rusefi/alphax-4chan/assets/48498823/53bc4665-98fe-4a59-b69f-c05b3f9ce98d)

please properly configure exhaust as engine sync cam
