### ISSUE TITLE
Rev. g AIN3 pulldown

### ISSUE THREAD

**Issue by Qwerty-OFF** [rusefi/alphax-4chan#137]
In addition to the pads in the pull-up configuration area for the AIN1-AIN4 inputs, the board has an additional 510k pull-down for the AIN3 line. In the standard board configuration, the pull-down on the AIN3 line is 290k. If a change is necessary, R232 should be removed and the required nominal should be soldered in the configuration area:
![image](https://github.com/rusefi/alphax-4chan/assets/4116383/63f69422-8e8e-4be4-9abc-99df92870070)

**Comment by Qwerty-OFF** [comment]
@rusefillc remove R232, also:
https://github.com/andreika-git/hellen-one/issues/295#issuecomment-1550187835

**Comment by ElDominio** [comment]
Can be closed?
