### ISSUE TITLE
RevH Tacho output not working but changing between 5v/12v

### ISSUE THREAD

**Issue by ElDominio** [rusefi/alphax-4chan#143]
As stated, tacho does not work (no wave on oscope) but switching voltage in Fancy Hardware DOES change voltage.

Was a pin changed from revF to revH to drive the tacho?

**Comment by rusefillc** [comment]
@ElDominio do you know resistance of that tach? Do you want me to get same real tachometer for tests?

**Comment by ElDominio** [comment]
Test 1: tacho output set to 12v and pin A4

![IMG_20230713_204952__01.jpg](https://github.com/rusefi/alphax-4chan/assets/5685108/18b5a46b-4aff-4f46-8689-e6e8f6eabd8b)

![IMG_20230713_204948.jpg](https://github.com/rusefi/alphax-4chan/assets/5685108/06027c13-d748-4a50-8420-e22b8226cfc0)

Test 2: tacho output using Aux10, internal 4chan

![IMG_20230713_205604__01.jpg](https://github.com/rusefi/alphax-4chan/assets/5685108/1d046c94-41e8-4c05-a837-5ddb976d9420)


![IMG_20230713_205540.jpg](https://github.com/rusefi/alphax-4chan/assets/5685108/c46f9ff4-408b-4f38-9386-cdb332444dbf)

**Comment by ElDominio** [comment]
Are scopes useful? Any update?
