### ISSUE TITLE
some pads are missing on GTP and GBP layer

### ISSUE THREAD

**Issue by rusefillc** [rusefi/alphax-4chan#144]
текущие файлы переименовал в alphax_4ch-h.original

давай оставим ревизию H всё-таки, но напишем на шёлкографии звёзводчку после H

![image](https://github.com/rusefi/alphax-4chan/assets/48498823/c9a313e4-41a2-4dae-aea3-8c8610ed3a4a)

**Comment by Qwerty-OFF** [comment]
Починил, использовал футпринт из библиотеки кикада
