### ISSUE TITLE
P1 adjust main connector DO NOT CLOSE UNTIL LIBRARY CHANGED

### ISSUE THREAD

**Issue by rusefillc** [rusefi/alphax-4chan#145]
the hole pitch is 4.2/4.2/3.33mm, GERBER is 4.0/4.0/3.5mm

@Qwerty-OFF мы можем сделать что-то универсальное? немного овальные отверстия может быть? я что-то могу намерять своими разъёмами полезного?

![image](https://github.com/rusefi/alphax-4chan/assets/48498823/1ac8edfb-f42c-4805-9575-46e527df325b)

**Comment by Qwerty-OFF** [comment]
Если ты сможешь измерить с точностью 0.2мм, давай узнаем сколько там должно быть на самом деле

**Comment by rusefillc** [comment]
[delphi_12042017_HCCPHPE24BKA90F-1224853.pdf](https://github.com/rusefi/alphax-4chan/files/12010120/delphi_12042017_HCCPHPE24BKA90F-1224853.pdf)

**Comment by rusefillc** [comment]
ха, внезапно он существует официальный и новый и в принципе его можно в JLC заказать

**Comment by Qwerty-OFF** [comment]
Сделал отверстия увеличенного размера для совпадения со старым вариантом и с тем что в документе.
@rusefillc Если все будет хорошо, заставь меня переложить модифицированный компонент в kicad6-libraries для дальнейшего использования

**Comment by Qwerty-OFF** [comment]
TODO использовать в следующей ревизии символ из библиотеки

**Comment by rusefillc** [comment]
https://github.com/rusefi/kicad6-libraries/commit/ccd7bead220f3861fc2b8eb6ab7e77dbb559d2a7
