### ISSUE TITLE
Has tacho drive pin changed from revision F to revision G?

### ISSUE THREAD

**Issue by ElDominio** [rusefi/alphax-4chan#146]
As stated in the title, I have reason to believe that the processor pin that drives tacho output has changed from revF to revG

related to #143

**Comment by Qwerty-OFF** [comment]
OUT_IO13 -> IO3

**Comment by rusefillc** [comment]
what you call IO3 is GP3 in https://github.com/rusefi/rusefi/blob/master/firmware/config/boards/hellen_meta.h :(
