### ISSUE TITLE
Pin Aux2 Inj5 in use  on revH

### ISSUE THREAD

**Issue by ElDominio** [rusefi/alphax-4chan#148]
<img width="489" alt="image" src="https://github.com/rusefi/alphax-4chan/assets/5685108/d57121fb-922f-42d4-b558-79e9aa4b9b4b">

please fix

can all the aux pins be fixed please

**Comment by rusefillc** [comment]
@Qwerty-OFF 
is it 
![image](https://github.com/rusefi/alphax-4chan/assets/48498823/5400d706-769c-4f76-8209-5494f921d814)
on rev H?

any similar changes?

**Comment by rusefillc** [comment]
@Qwerty-OFF see https://github.com/rusefi/rusefi/commit/d0fe15110ba836d89d7649e27137ad23607321fd

**Comment by Qwerty-OFF** [comment]
rev f. D2_PULLDOWN = OUT_INJ5 = PD9
rev h. D2_PULLDOWN = OUT_IO13 = PG6
