### ISSUE TITLE
rev H: Pin D3 Digital in 2, is processor pin correct? 

### ISSUE THREAD

**Issue by ElDominio** [rusefi/alphax-4chan#149]
I have a car using D3 Digital In 2 as AC input, i can see 12v on AC request and no voltage on no request, so everything is reaching ECU correctly, but I see no change in software.

**Comment by rusefillc** [comment]
![image](https://github.com/rusefi/alphax-4chan/assets/48498823/c1bf8d9a-8b63-47b8-b989-c2cceb609231)

![image](https://github.com/rusefi/alphax-4chan/assets/48498823/059d7f67-b317-4943-a0f9-1f36e46f6de5)

![image](https://github.com/rusefi/alphax-4chan/assets/48498823/fcb89fd3-b456-4b1d-aef0-2c3e19ce45ca)

**Comment by rusefillc** [comment]
^^^ does not match yaml

**Comment by rusefillc** [comment]
@ElDominio it's turning ugly :( see https://github.com/rusefi/rusefi/commit/baaec6ff328077994a03cd216287685844d2a026

@Qwerty-OFF FYI
