### ISSUE TITLE
Silkscreen IGND reads as "I-GND" not as "IGN-D"

### ISSUE THREAD

**Issue by rusefillc** [rusefi/alphax-4chan#15]
Also schematics says IGN4

let's change silk to follow schematics - from IGNA-D to IGN1-4

**Comment by andreika-git** [comment]
It was inherited from the original board:
![image](https://user-images.githubusercontent.com/15104768/161305973-fcddb427-29dc-4ef6-89ad-0e2eea484020.png)
Ok, let's change it to our numerical notation!

**Comment by rusefillc** [comment]
@ElDominio please approve IGN4

**Comment by ElDominio** [comment]
I approve this, it's better.

**Comment by andreika-git** [comment]
Do we need the same for INJA..INJD?

**Comment by rusefillc** [comment]
@ElDominio i guess yes on 4chan?

**Comment by rusefillc** [comment]
schematics says 1-4 for both

![image](https://user-images.githubusercontent.com/48498823/173048653-201e2135-62f8-4d1b-bd9b-362dd12a3686.png)

let's replace A-D with 1-4 on all silk

**Comment by andreika-git** [comment]
![image](https://user-images.githubusercontent.com/15104768/173080083-f2eba4c8-cbb8-44e3-ba22-2bcf6b78a65b.png)
![image](https://user-images.githubusercontent.com/15104768/173080186-5fe24a39-425e-414f-adac-18857d25bcf6.png)

Done
https://github.com/rusefi/alphax-4chan/commit/a3c0af0193ebfe586d35963ddcb781002348c70c
