### ISSUE TITLE
Pin E2 Out NOS not working, correct processor pin? On revH

### ISSUE THREAD

**Issue by ElDominio** [rusefi/alphax-4chan#150]
I am using for AC relay control. I can see 12v from the relay when blower is on, but no software change drives the transistor. Is the processor pin correct?

**Comment by rusefillc** [comment]
![image](https://github.com/rusefi/alphax-4chan/assets/48498823/59486671-ea07-4b19-9369-ed8c62530710)

**Comment by rusefillc** [comment]
![image](https://github.com/rusefi/alphax-4chan/assets/48498823/5b3ef47a-f15b-4c46-9f91-197aa73d18f4)

**Comment by rusefillc** [comment]
https://github.com/rusefi/rusefi/blob/162507ca0d06c26ecb05785335fa6bf32e597dbb/firmware/config/boards/hellen/alphax-4chan/connectors/main.yaml#L296

@Qwerty-OFF please confirm?

**Comment by Qwerty-OFF** [comment]
Yes that's right

**Comment by rusefillc** [comment]
@ElDominio we do not see any problems here need more info

**Comment by rusefillc** [comment]
@ElDominio any details?
