### ISSUE TITLE
maybe it kind of works [was Split packages for legacy 4chan (revF and before) and current 4chan (revG and above)]

### ISSUE THREAD

**Issue by ElDominio** [rusefi/alphax-4chan#152]
I updated a revF today and lost tach, which I suppose is because I had asked for #146 

Would it not be best to have two seperate packages for them? To avoid pinout problems?

My current fix:
Will downgrade to june release

**Comment by rusefillc** [comment]
https://github.com/rusefi/rusefi/commit/baaec6ff328077994a03cd216287685844d2a026

so we have two options for D3 now

"D3 - Digital In 2 legacy up to rev F"
"D3 - Digital In 2 (A4 tach out up to rev F)"

**Comment by ElDominio** [comment]
![image](https://github.com/rusefi/alphax-4chan/assets/5685108/c1c6374c-1809-4b86-9415-7bc289c50ecc)

I can't choose tach output in outputs menu telling it that it is a revF

**Comment by rusefillc** [comment]
Ohh stuff was not generating due to issue around https://github.com/rusefi/rusefi/pull/5412

**Comment by rusefillc** [comment]
@ElDominio pinout and stuff is more properly generated now

https://rusefi.com/docs/pinouts/hellen/alphax-4chan/?pin=D3

**Comment by ElDominio** [comment]
Pinouts between pre-RevG and RevG+ change, and my solution is to keep a July (20230705) firmware for when RevF downwards ECUs show up at my shop.
