### ISSUE TITLE
4chan stuck boot looping

### ISSUE THREAD

**Issue by ElDominio** [rusefi/alphax-4chan#153]
https://youtu.be/vtys1Co_DvI

Connected to 12v or USB, no change

Erased flash and flashed firmware again, no change.

**Comment by rusefillc** [comment]
@ElDominio revision? specific unit or two units? random firmware? please try release? latest?

**Comment by ElDominio** [comment]
RevH
07-28 snapshot
One unit for now, have not checked others

**Comment by rusefillc** [comment]
@ElDominio please ship to NJ I do not have other ideas

**Comment by ElDominio** [comment]
Will do

**Comment by rusefillc** [comment]
@ElDominio any news?

**Comment by ElDominio** [comment]
I have no idea where this 4chan went, closing
