### ISSUE TITLE
use 9924 on one of VR channels

### ISSUE THREAD

**Issue by rusefillc** [rusefi/alphax-4chan#160]

**Comment by ElDominio** [comment]
bumping

9924 is a godsend on CKP, not really on CMP. Discrete is very good at decoding lower tooth cam signals, and 9924 is not so

**Comment by Qwerty-OFF** [comment]
![image](https://github.com/rusefi/alphax-4chan/assets/4116383/5f8226f5-5abf-4f89-b322-60bb0f10467d)
Should I move the VR input from the previously used E5/E6? Is it necessary to maintain HALL support for the third VR input? The MAX9924 allows to natively use one of the lines as a HALL input, and this functionality can be activated either by manually soldering a resistor or programmatically with a number of additional components. To use both inputs as HALL, the scheme currently used for C2/C3 can be replicated.

**Comment by Qwerty-OFF** [comment]
The ability to enable pulldown on the C4/C7 lines will be removed. The pullup for use as a Hall sensor will be similar to the C2, C3, E6 lines.
