### ISSUE TITLE
document ETB capacitors

### ISSUE THREAD

**Issue by rusefillc** [rusefi/alphax-4chan#162]
https://github.com/rusefi/alphax-4chan/issues/110 has added electrolytic while not removing ceramic capacitors

we have never removed electrolytic from BOM even while https://github.com/rusefi/alphax-4chan/issues/110 was implying only footprint for custom board manual modification

At the moment all recent 4chan were fabricated with both sets? Is that a bug or a feature? Let's add text comment on the ETB page.

**Comment by rusefillc** [comment]
let's move optional (?) electrolytic capacitor from the reusable reusable page to 4chan main page and mention that it technically is not needed

**Comment by Qwerty-OFF** [comment]
Done, electrolytic capacitor is now DNP
![image](https://github.com/rusefi/alphax-4chan/assets/4116383/658877c3-de3b-46c4-8714-6588b3b1dfcb)
