### ISSUE TITLE
Make ETB page reusable

### ISSUE THREAD

**Issue by rusefillc** [rusefi/alphax-4chan#163]
Let's move ETB file somewhere
* I guess we would need version number in the file path just in case

**Comment by Qwerty-OFF** [comment]
https://github.com/andreika-git/hellen-one/blob/master/kicad/pages/DC_MOTOR_0.1.kicad_sch

**Comment by rusefillc** [comment]
да, есть некоторый бред. текущий бред объясняется историей - какая страницу откуда пришла, объяснение так себе

**Comment by rusefillc** [comment]
пока добавил readme.md файлики и закрыл
