### ISSUE TITLE
Tacho pin error with RevB

### ISSUE THREAD

**Issue by ElDominio** [rusefi/alphax-4chan#165]
<img width="576" alt="image" src="https://github.com/rusefi/alphax-4chan/assets/5685108/01199bfa-b0c7-4b24-97ec-e7a4dcbd127a">

**Comment by rusefillc** [comment]
@ElDominio I do not have any older revisions to test with

please ship me an old revision or let's close or let's fabricate some of old revision if important enough?

**Comment by ElDominio** [comment]
Related to #152
