### ISSUE TITLE
Make Battery Voltage read from A2 (main relay)  instead of F7

### ISSUE THREAD

**Issue by ElDominio** [rusefi/alphax-4chan#166]
<img width="940" alt="image" src="https://github.com/rusefi/alphax-4chan/assets/5685108/fb6da916-d285-48d8-ad7d-357af9d956da">
Pictured: Key input has 11.3v when battery has 12.1v

Using key input as battery voltage is incorrect since we base our Dwell and Injection dead time corrections off battery voltage, we should read from the same source. On most cars, key-on is usually a bit smaller voltage than main relay, but sometimes even 1v off.

**Comment by rusefillc** [comment]
@ElDominio this is harder than just a hardware change. At the moment we engage main relay when we sense voltage on ignition key.

if we only make the hardware change we would have to adjust 4chan settings to ALWAYS engage main relay which I assume is not desired.

For 4chan to read voltage from main relay we would need to ADD analog input not just MOVE.

@ElDominio looks like we would have to reuse one of aux analog inputs for main relay voltage. I suggest https://rusefi.com/docs/pinouts/hellen/alphax-4chan/?pin=X3

@ElDominio please confirm that we repurpose X3 analog input for main relay input

**Comment by ElDominio** [comment]
Can we not sense ignition ON voltage with a digital pin, then use analog to read voltage from A2?

**Comment by ElDominio** [comment]
I made a circuit to do this in one of my boards, if you want i can post it here (external main relay control)

**Comment by ElDominio** [comment]
<img width="504" alt="image" src="https://github.com/rusefi/alphax-4chan/assets/5685108/1e04a70e-52d8-4a95-8431-9715c5393dda">

just in case

**Comment by rusefillc** [comment]
![image](https://github.com/rusefi/alphax-4chan/assets/48498823/70770996-beff-4487-8085-637f02722962)

**Comment by rusefillc** [comment]
@ElDominio I do not have brain capacity to deal with this until January.

Do you want "rev-i" without this ticket in Dec or with it in January?

**Comment by ElDominio** [comment]
With it in January

**Comment by rusefillc** [comment]
```
#if EFI_MAIN_RELAY_CONTROL
	hasIgnitionVoltage = Sensor::getOrZero(SensorType::BatteryVoltage) > 5;
```

**Comment by rusefillc** [comment]
Let me remove R53 to test https://github.com/rusefi/rusefi/commit/3b88f847e0370de6afc359f88c7c315cf695689c

open question what pin to use for ignitionKeyDigitalPin

**Comment by rusefillc** [comment]
![WhatsApp Image 2023-12-10 at 12 58 40_4135a36b](https://github.com/rusefi/alphax-4chan/assets/48498823/56fc28d0-4217-4023-a50b-be79bf7e495c)

**Comment by Qwerty-OFF** [comment]
Схема не подойдет для вариантов где всегда (на заглушенной машине) есть напряжение на нашем vign входе, будет разряжать аккумулятор. Также измерение напряжения главного реле через резисторный делитель тоже будет расходовать заряд батареи. Для автомобилей у которых питание always hot и запуск по can wakeup надо придумать что-то лучше.

**Comment by rusefillc** [comment]
устал я от этой темы, я уже согласен на второй аналоговых вход

а можем ли мы сделать AV из AT1 например удалением резистора?

![image](https://github.com/rusefi/alphax-4chan/assets/48498823/66e92803-8cfc-4346-8608-e9bda95ec229)

**Comment by Qwerty-OFF** [comment]
Да, можно сделать av через replace

**Comment by rusefillc** [comment]
@Qwerty-OFF давай заведём main relay +12v на AT1 с делителем
