### ISSUE TITLE
3D pcb with main connector and USB

### ISSUE THREAD

**Issue by rusefillc** [rusefi/alphax-4chan#170]
хочется 3D разъёмов в первую очередь и usb-c во вторую

google for HCCPHPE24BKA90F says https://grabcad.com/library/sicma-hccphpe24bka90f-2

**Comment by Qwerty-OFF** [comment]
![image](https://github.com/rusefi/alphax-4chan/assets/4116383/44daec22-1940-4b2a-8597-7d25969e91f3)

**Comment by rusefillc** [comment]
чётрый и сервы разъёмы различаются стороной открытия, для наших целей 3Д прекрасен!
