### ISSUE TITLE
Kia start request - revisit external resistor

### ISSUE THREAD

**Issue by rusefillc** [rusefi/alphax-4chan#171]
this is about kia and start request did we have any other tickets?

![WhatsApp Image 2023-12-10 at 12 50 28_16dfc309](https://github.com/rusefi/alphax-4chan/assets/48498823/960ff9ba-eb49-4093-ac64-0f929bf9634d)

**Comment by ElDominio** [comment]
https://github.com/rusefi/rusefi/issues/5701#event-10914823433
