### ISSUE TITLE
Tacho pin in use on legacy tacho pin

### ISSUE THREAD

**Issue by ElDominio** [rusefi/alphax-4chan#174]
![image](https://github.com/rusefi/alphax-4chan/assets/5685108/332bce30-28dc-46be-9be8-abba892faa80)

**Comment by rusefillc** [comment]
@ElDominio is your opinion what the most valuable single piece of information which is missing here?

**Comment by ElDominio** [comment]
Latest firmware on 4chan F4 revB?

**Comment by rusefillc** [comment]
> revB?

this!

**Comment by ElDominio** [comment]
This works now!
