### ISSUE TITLE
fab rev i

### ISSUE THREAD

**Issue by rusefillc** [rusefi/alphax-4chan#177]
![chrome_8WERsGpHWg](https://github.com/rusefi/alphax-4chan/assets/48498823/558f7959-12cb-41f9-837a-fd3583cea9a8)

**Comment by rusefillc** [comment]
@Qwerty-OFF я тормозил и у JLC были глюки

![image](https://github.com/rusefi/alphax-4chan/assets/48498823/e19e60a5-a2b6-4c3d-96dd-6f038b61ba23)

**Comment by rusefillc** [comment]
@Qwerty-OFF теперь 1K


![chrome_0FvDUbPiDk](https://github.com/rusefi/alphax-4chan/assets/48498823/560c15ae-0697-4a33-9a5c-92c4df03a567)

C110021 вместо C425239?

**Comment by Qwerty-OFF** [comment]
> C110021 вместо C425239?

Да
