### ISSUE TITLE
Boot time has increased

### ISSUE THREAD

**Issue by ElDominio** [rusefi/alphax-4chan#178]
I updated a 4chan revG to latest and noticed booting takes much longer, do not have a video on hand at the moment. Some LEDs blink on power on, then after about 500ms it seems to reset and boot correctly. I can also hear sparks firing when it boots

**Comment by rusefillc** [comment]
@ElDominio noted, thank you! This is about openblt configuration.

Since no desires were articulated shall i vlose?

**Comment by ElDominio** [comment]
Can it be configured to boot as fast as possible? And not spark on startup
