### ISSUE TITLE
Q3 long term fix BOM or schematics?

### ISSUE THREAD

**Issue by rusefillc** [rusefi/alphax-4chan#18]
We would need same as https://github.com/rusefi/alphax-2chan/issues/52

**Comment by andreika-git** [comment]
![image](https://user-images.githubusercontent.com/15104768/173079936-b8491f6b-5bf3-4dda-8984-6c84a8190fd8.png)

Done
https://github.com/rusefi/alphax-4chan/commit/a3c0af0193ebfe586d35963ddcb781002348c70c

**Comment by rusefillc** [comment]
@mck1117 wanna review?

**Comment by mck1117** [comment]
simulation says with the existing circuit we can't exceed about -10.4 volts V_gs on Q3, up to 30v supply voltage.

The pullup functions correctly above ~9.5 volts battery voltage, so we're fine there too!
