### ISSUE TITLE
Fancy Hardware is not visible

### ISSUE THREAD

**Issue by ElDominio** [rusefi/alphax-4chan#181]
I cannot change pullups
![image](https://github.com/rusefi/alphax-4chan/assets/5685108/d66da0c7-e3f0-4a12-a37e-c21ae0b3b226)

![image](https://github.com/rusefi/alphax-4chan/assets/5685108/0286a452-0bd2-4b1e-a40e-9582cee64ecf)

**Comment by rusefillc** [comment]
![image](https://github.com/rusefi/alphax-4chan/assets/48498823/28cfcdb3-1a47-42f1-b75c-8d2cdabc3365)
