### ISSUE TITLE
Not enough memory on 4Chan F7 on a script that ran on F4?

### ISSUE THREAD

**Issue by ElDominio** [rusefi/alphax-4chan#186]
Isn't one of F7's primary benefits more lua? :(
![image](https://github.com/user-attachments/assets/5944f0f8-00d7-45f1-8cee-8f17e550b4fb)

**Comment by rusefillc** [comment]
@ElDominio closing because I see zero evidence for "Not enough memory on 4Chan F7 on a script that ran on F4" 

while I do see a weird MEMORY LEAK I believe that it has nothing to do with "Not enough memory on 4Chan F7 on a script that ran on F4"
