### ISSUE TITLE
Q3 hardware mod for rev A and rev B

### ISSUE THREAD

**Issue by rusefillc** [rusefi/alphax-4chan#19]
See https://github.com/rusefi/alphax-2chan/issues/53

**Comment by andreika-git** [comment]
There is also a suggestion to swap p-channel mosfets for vishay SI2347DS-T1-BE3 is similar but has 20V max V_gs part:
* Q3, Q4, Q5, Q16, Q17, **Q31, Q32**.

**Comment by rusefillc** [comment]
@andreika-git do we have JLCPBC suggestions maybe it's not too late to replace part in the current order

**Comment by andreika-git** [comment]
SI2347DS is perfectly available on JLC: C710065 or C145002

**Comment by rusefillc** [comment]
I've ordered all qty 14 of SI2347DS-T1-BE3 available on Mouser

need more to fix the 10 units of rev A I am receiving

**Comment by rusefillc** [comment]
@andreika-git says 726-BSS308PEH6327

**Comment by rusefillc** [comment]
@andreika-git just to confirm that Q18 is NOT affected?

**Comment by andreika-git** [comment]
> @andreika-git just to confirm that Q18 is NOT affected?

Yes, it has 3.3v which is < 12v
