### ISSUE TITLE
C4 digital input to support more modes

### ISSUE THREAD

**Issue by rusefillc** [rusefi/alphax-4chan#2]
At the moment C4 digital input is hall only

@ElDominio is asking for that to support 12v/5v/gnd input

@andreika-git do we already support 12v/5v/gnd with software-configurable pull-up?

**Comment by andreika-git** [comment]
> @andreika-git do we already support 12v/5v/gnd with software-configurable pull-up?

Currently "C4" has no software-configurable pull-up, it has only 5v fixed pull-up but is fully 12v-tolerant (as well as other inputs).

**Comment by rusefillc** [comment]
See https://github.com/rusefi/alphax-2chan/issues/32

**Comment by ElDominio** [comment]
Close?
