### ISSUE TITLE
was [rev B test log] now let's restore that test board

### ISSUE THREAD

**Issue by rusefillc** [rusefi/alphax-4chan#20]
does not DFU as arrived from JLC

This is different from https://github.com/rusefi/alphax-2chan/issues/47 since no USB power surge and a number of LEDs are ON, just no DFU

**Comment by rusefillc** [comment]
With USB power, 3v regulator gets 3.6v input instead of expected 4.8v input

with 3.6v input 3v generator outputs about 0.1v

**Comment by rusefillc** [comment]
keweisi usb detector says 1.6A

hottest area SEEMS to be between MCU module and VR module but hard to say with more precision :( i think back side gets cooler when I touch it, i take all the heat?

**Comment by rusefillc** [comment]
3v regulator U101 seemed like the hottest part

I've removed U101 and consumption went down to 0.17A

**Comment by rusefillc** [comment]
with U101 removed 3v to ground beeps, seems to be about 1 ohm

**Comment by rusefillc** [comment]
found issue it was similar to Harley defect

root cause lack of automated validation https://github.com/andreika-git/hellen-one/issues/152

**Comment by rusefillc** [comment]
it was a gerber issues with a via under  C461

![image](https://user-images.githubusercontent.com/48498823/169161809-a0e984b2-ee85-4afb-be7a-9093161116c4.png)

Q: how happy is this ECU going to be without C461?

![image](https://user-images.githubusercontent.com/48498823/169161890-ecdddb37-2db0-4645-8948-0d3a1dd866e7.png)

**Comment by rusefillc** [comment]
gerber issue around Ign fixed by https://github.com/rusefi/alphax-4chan/commit/38b9e8fdefc0ad3ff9537dbe6887440f12287586

**Comment by rusefillc** [comment]
three cuts total

![image](https://user-images.githubusercontent.com/48498823/176994868-960329f2-dfe7-4628-8274-7cbdc5971af2.png)

![image](https://user-images.githubusercontent.com/48498823/176994880-8cf6e437-9ef2-40ab-ada5-8d02410770aa.png)


![image](https://user-images.githubusercontent.com/48498823/176994885-0462f5d3-4f6b-495c-8a1a-392d15bf27b0.png)

**Comment by rusefillc** [comment]
![image](https://user-images.githubusercontent.com/48498823/178289731-1da6a3d0-d325-4def-9d51-d973e52f1531.png)

![image](https://user-images.githubusercontent.com/48498823/178289770-8acb4749-a004-431e-8ee3-ba08ca0721b4.png)

**Comment by ElDominio** [comment]
I need to do this to revB 4chan I suppose?

**Comment by rusefillc** [comment]
@ElDominio short answer is NO

**Comment by ElDominio** [comment]
Close?
