### ISSUE TITLE
Bump all module versions

### ISSUE THREAD

**Issue by rusefillc** [rusefi/alphax-4chan#21]
ign8 is not latest maybe some other modules as well?

**Comment by rusefillc** [comment]
https://github.com/andreika-git/hellen-one/issues/153

**Comment by andreika-git** [comment]
![image](https://user-images.githubusercontent.com/15104768/173079775-acea4164-875b-4428-aee6-c1ec600e6def.png)

Done
https://github.com/rusefi/alphax-4chan/commit/a3c0af0193ebfe586d35963ddcb781002348c70c
