### ISSUE TITLE
4chanB shipment

### ISSUE THREAD

**Issue by rusefillc** [rusefi/alphax-4chan#22]
shipping x8 of 4chanB, all programmed and BT initialized

x2 have seven p-mosfets removed as examples, the rest have OLD p-mosfets please upgrade all boards to new p-mosfets (supplied) se ehttps://github.com/rusefi/alphax-4chan/issues/19

MAP included not soldered
TLS115 included not soldered

**Comment by rusefillc** [comment]
@ElDominio says some components were lost and should be shipped

**Comment by ElDominio** [comment]
Close
