### ISSUE TITLE
ETB heat management: More vias under ETB chip? copper somewhere?

### ISSUE THREAD

**Issue by rusefillc** [rusefi/alphax-4chan#24]
@mck1117 suggests more vias under ETB chip

can we actually have huge holes to facilitate soldering with limited tools?

4chan at the moment
![image](https://user-images.githubusercontent.com/48498823/170130266-8b418db8-52e7-42f2-8c79-095bbdecdf4f.png)

probably Proteus
![image](https://user-images.githubusercontent.com/48498823/170130305-718da97f-1843-40d1-ae8d-98ba9a2755ab.png)

**Comment by rusefillc** [comment]
@ElDominio reports issues during calibration, we need an incremental improvement.

```
overheat
a few cars have had issues BUT, not driving
couldn't the underside have a bit of copper to solder it onto for heat dissipation?
```

My question: can we make LARGE vias like 1.5mm to give a chance to solver through back side to make soldering simpler?

**Comment by ElDominio** [comment]
About soldering, I have a guy that solders them PERFECTLY now. This improved the situation but did not fix it.

**Comment by mck1117** [comment]
Proteus has 3 ground planes, and tons of vias under the chips, and has no overheating problem.

**Comment by rusefillc** [comment]
@mck1117 @Qwerty-OFF please review

**Comment by rusefillc** [comment]
@andreika-git says that connected polygon could make it too hard to solder in terms of heat requirmen
