### ISSUE TITLE
rev.C release candidate is ready

### ISSUE THREAD

**Issue by andreika-git** [rusefi/alphax-4chan#27]
@ElDominio 
@rusefillc 

https://github.com/rusefi/alphax-4chan/commit/e9edac8526493315d7f32acaf8e4a230b21bd85e

Can you please review?

**Comment by ElDominio** [comment]
I only wonder if .3mm on the connectors is too much? Besides that all fixes look good

**Comment by rusefillc** [comment]
@ElDominio i see that connectors are hugging middle piece but I see gaps on outside. I've done some measurments it looks like 0.3 apart on both would get us much close to middles of case openings

**Comment by ElDominio** [comment]
Understood. I have only done eye measurements so I'll take your word for it
