### ISSUE TITLE
rev C BOM state

### ISSUE THREAD

**Issue by rusefillc** [rusefi/alphax-4chan#28]
1. let's remove R40 since we always use TLS115

![image](https://user-images.githubusercontent.com/48498823/173141055-dc0c87ca-0b82-4f85-8959-7c48a3a292b1.png)

2. need alternative for F101
![image](https://user-images.githubusercontent.com/48498823/173141059-e8bb847e-3284-40b7-9831-8afa3fc41ec9.png)

3. no action needed, just FYI - I am out of parts in library, trying to order more. I have ebay parts

![image](https://user-images.githubusercontent.com/48498823/173141247-4b6e596c-502a-4cf0-82dd-0beb34abf372.png)

4. let's remove from BOM to reduce distraction or find some way to mark so that it's less visible

![image](https://user-images.githubusercontent.com/48498823/173140989-20f75e41-a47b-4dcc-810c-afa1fc3f1742.png)

**Comment by rusefillc** [comment]
5. C87403 is in stock but it's 20% of total board price?!

**Comment by andreika-git** [comment]
A possible replacement for C87403 is C213161.

**Comment by mck1117** [comment]
looks like C213161 is a bit slower, but still probably OK

**Comment by rusefillc** [comment]
I now own some C213161 in parts library

**Comment by rusefillc** [comment]
DaveB says:

[C92485](https://lcsc.com/product-detail/Analog-Switches-Multiplexers_Texas-Instruments-TS5A3159DBVR_C92485.html) 

C10426 ? C255474 ?





[12:08](https://rusefi.slack.com/archives/CKG9KQHS7/p1654920503226719)
C255474
