### ISSUE TITLE
rev C - low stock and not cheap SN74LVC2G17DCKR C50714

### ISSUE THREAD

**Issue by rusefillc** [rusefi/alphax-4chan#29]
any cheaper than $3 and qty 103 C50714 alternatives?

http://www.ti.com/cn/lit/gpn/sn74lvc2g17

![image](https://user-images.githubusercontent.com/48498823/173168482-43e78df7-dbaf-46ec-b23b-a919ccce8e01.png)

**Comment by rusefillc** [comment]
@andreika-git do we have options in same or smaller packages?

**Comment by andreika-git** [comment]
The same package, the cheapest but low stock: C94189
The same package, rather expensive but more stock: C80500

**Comment by rusefillc** [comment]
i now own x65 of C94189

**Comment by rusefillc** [comment]
Dave mentions [C458779](https://jlcpcb.com/parts/componentSearch?isSearch=true&searchTxt=C458779)

this nexperia partis cheap ($0.16) on a reel.  depending on how many you use, may be worth global sourcing  supply sucks right now, but sourceengine has a ton. mouser has 80ish

extreme part shortage of all parts in this package.  I would be looking at alternative packages or possibly a quad or single vs. dual buffer

**Comment by rusefillc** [comment]
New separate issue https://github.com/rusefi/alphax-4chan/issues/32

**Comment by mck1117** [comment]
C80500 WILL NOT work - not rated for use of the high side diodes

**Comment by mck1117** [comment]
[C458779](https://jlcpcb.com/parts/componentSearch?isSearch=true&searchTxt=C458779) will not work since it's 3.3v only, and has no high side diodes either.

**Comment by mck1117** [comment]
Actually - the original part C50714 doesn't work either since it has no high side diodes!

**Comment by mck1117** [comment]
we must use C94189

**Comment by rusefillc** [comment]
qty 500 of 74HC2G17GW,125 https://jlcpcb.com/parts/componentSearch?isSearch=true&searchTxt=C94189 has arrived to NJ
