### ISSUE TITLE
cam/crank big picture

### ISSUE THREAD

**Issue by rusefillc** [rusefi/alphax-4chan#3]
What is the big picture? how many cam/crank in what combinations are we trying to support?

are we trying to support

VR+VR
VR+Hall
Hall+Hall

or more than that?

**Comment by rusefillc** [comment]
here's part of the current confusion

![image](https://user-images.githubusercontent.com/48498823/156434002-a01d4f59-c771-43c7-b471-99ad59015bc6.png)

**Comment by ElDominio** [comment]
So, the thing here is:

2chan supports crank Hall/VR, Cam hall only on black connector (the only one present here)

4chan supports crank Hall/VR, Cam Supports Hall/VR (on gray connector), and a secondary Cam input (on the black connector) as Hall only, for dual VVT.

**Comment by rusefillc** [comment]
So what setups are needed on top of
VR+VR
VR+Hall
Hall+Hall

It looks like we need 
Hall+Hall+Hall (@ElDominio please explicitly confirm 3xHall need)
and
VR+2xHall (@ElDominio please explicitly confirm VR+2xHall)

I am assuming that there is no car with VR+VR+Hall?

**Comment by ElDominio** [comment]
VR+Hall+Hall (some Hyundai have VR crank, Hall on both cams)
and Hall+Hall+Hall (4b11, hyundai theta g4kf)

VR+VR+VR i'd handle by using a MAX based converter for one of the cams

**Comment by rusefillc** [comment]
VR+Hall+Hall: VR+Hall same as on 2chan + Hall on grey B6

Hall+Hall+Hall:
Hall+Hall same as on 2chan + Hall on grey B6

VR+VR+Hall: VR on grey B5B6

**Comment by ElDominio** [comment]
Exactly

**Comment by rusefillc** [comment]
@ElDominio that raises the question of LED silkscreen

what labels do we use for all trigger-related LEDs on 4chan?

**Comment by ElDominio** [comment]
I suppose the black connector CAM input is CMP2, could be called CMP2 on both?
Crank = CKP
Cam on black connector = CMP2
Cam on gray connector = CMP

**Comment by ElDominio** [comment]
ok then

CKPVR(led1)
CKP+(led2)
CKP-(led3)

CMPVR(led4)
CMP+(led5)
CMP-(led6)

CMP2(led7)

**Comment by andreika-git** [comment]
Thanks! (I've edited the list 'cause we don't have CMP- hall)
