### ISSUE TITLE
BOM are all AO3401A the same?

### ISSUE THREAD

**Issue by rusefillc** [rusefi/alphax-4chan#30]
basic part without fee is five times the price of extended price 

![image](https://user-images.githubusercontent.com/48498823/173168884-12b89596-ba7d-4bea-908b-220c6d8fe6c3.png)

but overall damage is pretty low

![image](https://user-images.githubusercontent.com/48498823/173168927-4705fd6d-01b0-45f0-88b8-40a070554afc.png)

**Comment by andreika-git** [comment]
We can replace them all with C700953.

**Comment by rusefillc** [comment]
purchased C700953 for parts library
