### ISSUE TITLE
BOM are all AO3400A the same?

### ISSUE THREAD

**Issue by rusefillc** [rusefi/alphax-4chan#31]
![image](https://user-images.githubusercontent.com/48498823/173168968-edea5d6b-e612-4661-9b8d-b87e01af7560.png)

$50 here $50 there :)

![image](https://user-images.githubusercontent.com/48498823/173168974-c80a6e22-2308-4a0b-8090-bb66b0738414.png)

**Comment by andreika-git** [comment]
We can replace them all with C700954.

**Comment by rusefillc** [comment]
purchased C700954
