### ISSUE TITLE
huge vias for Q7 and friends

### ISSUE THREAD

**Issue by rusefillc** [rusefi/alphax-4chan#33]
we have a clear pattern where thermal pads are asking for above average soldering skills - ETB chip on all boards, PT2001 on GDI4 etc

can we add one or two 1mm via under Q7 and frends since those are now NOT JLC assembled as before?

**Comment by rusefillc** [comment]
Same question for "SOIC" TLS115

**Comment by ElDominio** [comment]
I'd say prioritize heat management over ease of soldering, I did find a much better soldering guy locally that will take care of this when needed.  He repairs phones/laptops and has experience in BGA reflowing and such

**Comment by rusefillc** [comment]
![image](https://user-images.githubusercontent.com/48498823/173233335-267a5e73-daf3-4d77-9393-fbcd6b686e84.png)
