### ISSUE TITLE
Main relay control not working properly

### ISSUE THREAD

**Issue by ElDominio** [rusefi/alphax-4chan#36]
I can't get a log but I can get a video. Main relay control works once, then after turning the key back on, the ECU seems to hang, I cannot connect to it through USB until I unplug it from the car and plug it back in`
More testing:
if i keep the laptop plugged in, key off, then unplug USB, the ecu shuts off;
if the laptop is unplugged, th ecu will stay turned on, and the next time i connect it is unresponsive until i fully disconnect the main harness and reconnect

**Comment by rusefillc** [comment]
any board or specific board?

are you personally there?

**Comment by ElDominio** [comment]
Yep, it's the Lancer I am testing. RevA 4Chan

**Comment by rusefillc** [comment]
Thank you for answering the second question!

Do you have more 4chan units you can try on same vehicle? i.e. is this issue specific to one board or any board is affected?

**Comment by ElDominio** [comment]
I do, I'll do that on Thursday too

**Comment by ElDominio** [comment]
About this:

Apparently, when battV is below a certain point, main relay control fails. Charged the battery up and now it's working as expected

**Comment by ElDominio** [comment]
For some reason, when battery voltage was about 10.8v, the ECU would just hang. Now that the battery is charged it works as expected

**Comment by rusefillc** [comment]
@ElDominio close this one?

**Comment by ElDominio** [comment]
Will run some more tests tomorrow and comment back on this

**Comment by ElDominio** [comment]
Close this since it was discovered this is a Lua issue, not a 4chan issue.

**Comment by rusefillc** [comment]
See https://github.com/rusefi/rusefi/issues/4322
