### ISSUE TITLE
Tach voltage not +12v

### ISSUE THREAD

**Issue by rusefillc** [rusefi/alphax-4chan#38]
with D1 removed voltage is 9.9v

with R46 value lowered to 470 tach voltage 11.5v

**Comment by andreika-git** [comment]
https://github.com/rusefi/alphax-4chan/commit/4de32993da84c7dde138b381038f24e7c7060564

![image](https://user-images.githubusercontent.com/15104768/180613367-cd682682-62a6-4e75-8189-ba7775861374.png)

**Comment by ElDominio** [comment]
RevE still not ok

In 12v mode, still spitting out around 4v![IMG_20230202_130255.jpg](https://user-images.githubusercontent.com/5685108/216392537-04c1c8de-3301-4c1b-966d-ba37fc2c5127.jpg)

**Comment by rusefillc** [comment]
Первый шаг отпаять D1 или D9 (светодиод TACH)

![WhatsApp Image 2023-02-02 at 13 17 56](https://user-images.githubusercontent.com/48498823/216432434-86a96ff6-e348-4f5a-bda0-5a5a93e579ac.jpg)

Второй посмотреть осциллографом что происходит на левой ноге R47

**Comment by rusefillc** [comment]
Baseline test in NJ

1R load
actual result:
tach LED does not blink
0v<>1v square wave with "5v" tach mode
0v<>2v square wave with "12v" tach mode

**Comment by rusefillc** [comment]
removed D9
nothing has changed - same 0/1 or 1/2v levels

left side of R47 constant 12v

**Comment by rusefillc** [comment]
1K load was a BAD TEST

without any load, with D9 removed I have happy 0v/+12v on tach output!

now going to return D9 since did not test without load :(

**Comment by rusefillc** [comment]
@ElDominio it seems to work fine on bench

@Qwerty-OFF says it could be about your specific resistance on specific tach.


@ElDominio can you please try with tach disconnected - would it be 9v or 12v without tach?
@ElDominio can you measure tach resistance to GND?

**Comment by ElDominio** [comment]
Hi, in the local tests I have done:

1) With nothing connected, it behaves as expected
2) With an older 12V tach, voltage drops as seen on the scope, tach does not move
3) Works fine with logic based tachs (5v), since they seem to only use the square wave to drive a motor
4) In 12V cases, we usually use the 5v output to drive a N2222 transistor pulled up to 12v, which then is used to drive the tacho. This works fine

**Comment by rusefillc** [comment]
@ElDominio are you looking for any changes on rev G like making the N2222 official right on the board? not sure if things would stay configurable

@ElDominio the safest option would be to provision for maybe even through hole N2222 right on 4chan but have it not populated by default, would you like that?

**Comment by ElDominio** [comment]
Having space for a 2222 THT, sounds at least like a _decent_ fix to make it _somehwat_ configurable, and I'd like it in all boards, I had totally forgotten about this

**Comment by Qwerty-OFF** [comment]
Now we have a transistor like N2222 pulled up to 5V. It can also be pulled up to 12V by additional control signal from MCU. What needs to be added?
![image](https://user-images.githubusercontent.com/4116383/226142779-e63bb555-b515-4063-be91-d36703eeac82.png)

**Comment by ElDominio** [comment]
So when I have issues with 12v tach, I usually use the Tach output on the ECU to drive a 2222 pulled up to 12V on the output, and then this produces a clean 12v square wave

**Comment by ElDominio** [comment]
Pullup is 1k

**Comment by Qwerty-OFF** [comment]
Configurable pullup:
![image](https://user-images.githubusercontent.com/4116383/229368600-7eae49b2-4d60-4a80-b0e9-aa6c7534def9.png)
Low-side MOSFET:
![image](https://user-images.githubusercontent.com/4116383/229368639-179599fe-ba6a-4721-ab6c-9f49cadc988d.png)

**Comment by rusefillc** [comment]
Reopening to game more notes

**Comment by ElDominio** [comment]
RevG can change voltages just fine
