### ISSUE TITLE
Review Schematics

### ISSUE THREAD

**Issue by rusefillc** [rusefi/alphax-4chan#4]
@ElDominio please validate schemaics

**Comment by ElDominio** [comment]
![image](https://user-images.githubusercontent.com/5685108/158070301-4ea4381f-56e8-4b25-ab9e-b2d8d5518b5b.png)

how do

**Comment by rusefillc** [comment]
@ElDominio are you using kicad 6.0?

did you do "git submodule update --init"

**Comment by ElDominio** [comment]
Updated Kicad to 6.0 and got to see it, everything looks swell

The only thing I don't understand how it works is the Key 12V in, both that one and main 12V turn the ECU on right? Key12V wakes up the ECU so it turns on main relay and recieves 12v (I tried double clicking the module M1 and it doesn't step into the module)
