### ISSUE TITLE
dual side mount means SD card

### ISSUE THREAD

**Issue by rusefillc** [rusefi/alphax-4chan#40]
not sure if 4chanD is best area to do our first test of dual sided but overall we shall leverage dual sided to get SD card

**Comment by andreika-git** [comment]
https://github.com/rusefi/alphax-4chan/commit/4de32993da84c7dde138b381038f24e7c7060564

![image](https://user-images.githubusercontent.com/15104768/180613386-fefab683-0dd4-444c-bf8e-ccb7871bcb5e.png)

![image](https://user-images.githubusercontent.com/15104768/180613434-2a5ee37c-df8d-4027-874a-e06ddf37b778.png)

We need to test if the BOM is generated correctly. Maybe fix it by hand for J9 and R96
