### ISSUE TITLE
black or grey? schematics usability

### ISSUE THREAD

**Issue by rusefillc** [rusefi/alphax-4chan#42]
![image](https://user-images.githubusercontent.com/48498823/180495160-52766f1f-3221-493e-8bcd-77428f60693d.png)

![image](https://user-images.githubusercontent.com/48498823/180495189-db4f2c2f-5155-491e-9f4c-bd0349850abb.png)

if we use same PN please spell "black" for P1 and "grey" for P2

**Comment by andreika-git** [comment]
https://github.com/rusefi/alphax-4chan/commit/4de32993da84c7dde138b381038f24e7c7060564

![image](https://user-images.githubusercontent.com/15104768/180613512-006dff82-348d-4670-86fc-0b173f66b029.png)
