### ISSUE TITLE
Can we try TSON-10 TLS115

### ISSUE THREAD

**Issue by rusefillc** [rusefi/alphax-4chan#43]
We plan a smallish batch do we have confidence to go TLS115 TSON-10?

As a module https://github.com/andreika-git/hellen-one/issues/167 or manually?

**Comment by rusefillc** [comment]
TLS115D0LDXUMA1
MFR.Part #
TLS115D0LDXUMA1
Manufacturer
INFINEON TECHNOLOGIES
JLCPCB Part #
C9900011264
Description
Linear Voltage Regulator IC Positive Adjustable 1 Output 150mA PG-TSON-10
Datasheet
Min. assembly qty
15pcs
Attrition
4pcs

**Comment by rusefillc** [comment]
Let me discuss with @ElDominio

**Comment by rusefillc** [comment]
@andreika-git please move forward

**Comment by andreika-git** [comment]
![image](https://user-images.githubusercontent.com/15104768/181711589-28d43f28-72d8-47c1-92d1-23e8df7ddf27.png)

![image](https://user-images.githubusercontent.com/15104768/181711773-a5c6e134-65da-417e-b2d3-2bf98e670ff3.png)
![image](https://user-images.githubusercontent.com/15104768/181711869-32bc609d-c761-4319-8d51-cdde10dea75a.png)

"TLS115","U1","hellen-one-common:PG-TSON-10-2","C9900011264"
