### ISSUE TITLE
one last round of manual gerber validation

### ISSUE THREAD

**Issue by rusefillc** [rusefi/alphax-4chan#47]
4chan rev D is the first hellen merge with assembly on both sides, we need an extra layer of human validation

**Comment by rusefillc** [comment]
@Qwerty-OFF please manually review generated gerbers around SD card on the back side if you can

**Comment by rusefillc** [comment]
@Qwerty-OFF пожалуйста сначала предложи вариант, но не меняй файлы - там потенциально @andreika-git будет другие изменения делать, нужна будет координация

**Comment by Qwerty-OFF** [comment]
Looks good
