### ISSUE TITLE
JLC assembled ideas for Schmitt-trigger

### ISSUE THREAD

**Issue by rusefillc** [rusefi/alphax-4chan#49]
We have four channels of Schmitt-trigger 

![image](https://user-images.githubusercontent.com/48498823/180809272-e1737be0-d7da-462a-bb25-59b10b912561.png)

now that we have double sided assembly do we have _any_ fully JLC options?

**Comment by rusefillc** [comment]
Still related to https://github.com/rusefi/proteus/issues/1 :)

**Comment by rusefillc** [comment]
@Qwerty-OFF пожалуйста сначала предложи вариант, но не меняй файлы - там потенциально @andreika-git будет другие изменения делать, нужна будет координация

**Comment by Qwerty-OFF** [comment]
74HC14 шестиканальный инвертирующий (видимо придется менять софт, был неинвертирующий)
74HC1G14 одноканальный инвертирующий
Либо ставить двухканальный аналогичный тому что уже есть, но без защиты, защиту поставить отдельно, снизу место есть.

**Comment by rusefillc** [comment]
@Qwerty-OFF лучше всего вариант защиту поставить отдельно, снизу место есть.

@andreika-git как скоординировать изменения?

**Comment by rusefillc** [comment]
@andreika-git can you add external protection on the back or do prefer that @Qwerty-OFF implements it?

**Comment by andreika-git** [comment]
I'll do. Perhaps, I'll use tree BAT54S...

**Comment by andreika-git** [comment]
![image](https://user-images.githubusercontent.com/15104768/181711320-99cf3ad5-1d5a-4632-bfcd-1ff2ea00df6a.png)
![image](https://user-images.githubusercontent.com/15104768/181711426-9b1febe6-05f4-41af-9ba6-6231cbf7147c.png)

# trigger schmidt buffer
"U2,U5","74LVC2G17GW","SOT-363","C80500"
