### ISSUE TITLE
Let's reduce pinout confusion

### ISSUE THREAD

**Issue by rusefillc** [rusefi/alphax-4chan#5]
At the moment we have black pin C4 and grey pin C4 that's confusing 

is it not too late to rename grey A-B-C to D-E-F? so that we have only black C4 and only grey F4?

**Comment by ElDominio** [comment]
That's fine by me, the connectors themselves have tiny litters that say ABC but we should still use D-E-F and let people figure it out

**Comment by andreika-git** [comment]
done
https://github.com/rusefi/alphax-4chan/commit/9b7ea558e700901db5528ae760adc1d8b6c80d22
