### ISSUE TITLE
voltage gauge is way off, revA

### ISSUE THREAD

**Issue by ElDominio** [rusefi/alphax-4chan#57]
![image](https://user-images.githubusercontent.com/5685108/184151439-6a8e2083-7e2a-4691-81bc-7b73cdd7c453.png)

Car is measured to be at 14.3V. 

This is not a car I have in person, install was done by client

**Comment by rusefillc** [comment]
need tune URL to see his battery correction coefficient
need a very short log URL but damn does not look like we log rawBvatt? :(
in rusEFI console we have ``analoginfo`` command which would post both need that info please

**Comment by mck1117** [comment]
@ElDominio can we get a photo of the pcb?

**Comment by rusefillc** [comment]
@ElDominio poke

**Comment by ElDominio** [comment]
The owner has not mentioned this again and as such, I have no updates lol

**Comment by rusefillc** [comment]
@ElDominio close or keep open?

**Comment by ElDominio** [comment]
Close
