### ISSUE TITLE
4chanD SD pinout is broken :(

### ISSUE THREAD

**Issue by rusefillc** [rusefi/alphax-4chan#59]
proper pinout

![image](https://user-images.githubusercontent.com/48498823/185718595-406527cc-c10f-4e21-963d-8f1f62a1cc8b.png)

and we have SCK and CS messed up

![image](https://user-images.githubusercontent.com/48498823/185718612-74fb14a9-1ad0-4546-b496-867dfe7af9d5.png)

**Comment by andreika-git** [comment]
fixed in rev.E
