### ISSUE TITLE
Need help with order

### ISSUE THREAD

**Issue by rusefillc** [rusefi/alphax-4chan#6]
1) Need readme.md - I've tried https://github.com/rusefi/alphax-4chan/commit/66a8294935f5b3bb975d544b94274169caa9a0c5

2) own stock is now on second sheet of https://docs.google.com/spreadsheets/d/1b7IPYyfKyIHk4CH44ngV3pRVWT6DP8RQN10WxqnUWNQ 
```
STM32F427ZGT6 | C117816
VND14NV04TR-E | C2649436
```

3)
![image](https://user-images.githubusercontent.com/48498823/158287647-51e13bce-1a77-4704-887e-1d60599902a4.png)

**Comment by andreika-git** [comment]
Done.
https://github.com/rusefi/alphax-4chan/commit/668f75098c2acb54e3ce3a8962dfbc74fdca7b5e
Please note: 4 layers!
