### ISSUE TITLE
CRANKs/CAMs input hookup points

### ISSUE THREAD

**Issue by rusefillc** [rusefi/alphax-4chan#61]
Do we have test pads to hook up logic analyzer between VR/Hall conditioners and MCU on 4chan?

Can we add at least surface pads at least on the back?

**Comment by rusefillc** [comment]
https://github.com/rusefi/alphax-8chan/issues/11

**Comment by ElDominio** [comment]
For 2chan too!

**Comment by andreika-git** [comment]
Added test pads to the bottom side:
![image](https://user-images.githubusercontent.com/15104768/188500839-1cea2332-252d-408f-842f-50d02ca179d7.png)
