### ISSUE TITLE
Official wire colors

### ISSUE THREAD

**Issue by rusefillc** [rusefi/alphax-4chan#62]
@ElDominio do you have a PDF somewhere matching your paper instructions?

![image](https://user-images.githubusercontent.com/48498823/186939861-bf6c5c59-bf83-41ba-a99d-4e179a84a925.png)

I assume we want to match with https://rusefi.com/docs/pinouts/hellen/alphax-4chan/

**Comment by rusefillc** [comment]
"blue" but not blue

![image](https://user-images.githubusercontent.com/48498823/186940291-48603b1b-3b52-41bf-98da-b90912917c8e.png)

**Comment by ElDominio** [comment]
![backpostcard](https://user-images.githubusercontent.com/5685108/186940945-84ecf4e4-cfee-4423-82d8-ae692ef69429.png)

**Comment by ElDominio** [comment]
Close?

**Comment by ElDominio** [comment]
Why was it reopened?
