### ISSUE TITLE
What component to remove to ECU does not stay powered with a constant 12V source on an output

### ISSUE THREAD

**Issue by ElDominio** [rusefi/alphax-4chan#63]
On the PNP unit I made for Lancer X, A/C Clutch control is connected to F1 (Idle2). On the revA 4chan I was instructed to remove a component to make the ECU shut down properly, but I don't remember which one it is. Now that I am swapping to RevC I need to remove it again for the same effect.

**Comment by rusefillc** [comment]
@mck1117 were you involved with this? Do you recall what was this about?

Would be nice to get to the more bottom bottom of this :)

**Comment by ElDominio** [comment]
![image](https://user-images.githubusercontent.com/5685108/188488543-81687794-29de-422a-92ad-fc172ecf0acc.png)

**Comment by rusefillc** [comment]
@ElDominio is this A/C clutch PWM or on/off?

Anyway this or similar has happened enough of times that it needs to be understood more completely. Why does it happen for some outputs on some vehicles but no on others?

I am sure I had something like this on NB2 miata VVT, I am sure that I have back-feed on my Passat B6


@andreika-git @Qwerty-OFF @mck1117

**Comment by ElDominio** [comment]
On/Off 
Lancer 2009 N/A

The clutch relay has 12v at all times, if D51 is not removed, the ECU gets 12V from this output and turns on. Removing D51 removes this bad behavior, but probably gives problems with PWM. Since this output does not need to be PWM'd, this is fine.

**Comment by rusefillc** [comment]
We are lucky here this time but there is the wider pattern.

Is this about A/C being connected to battery directly not sitting behind main relay?

**Comment by rusefillc** [comment]
https://github.com/rusefi/rusefi_documentation/blob/master/OEM-Docs/Mitsubishi/2009-Lancer-Enginers-2L-turbo-2L-NA-2.4L-NA.pdf

**Comment by ElDominio** [comment]
Stupid Github phone app

Yes, it is because what you said

**Comment by ElDominio** [comment]
Can be closed

**Comment by ElDominio** [comment]
@rusefillc @Qwerty-OFF what is the equivalent of d51 in revH?

**Comment by Qwerty-OFF** [comment]
D66 for IDLE2 / F1 pin

**Comment by rusefillc** [comment]
https://github.com/andreika-git/hellen-one/issues/368
