### ISSUE TITLE
map sensor orienstation dot

### ISSUE THREAD

**Issue by mck1117** [rusefi/alphax-4chan#64]
dot should be the same as dot on 2chan, so that MAP sensors aren't backwards

**Comment by andreika-git** [comment]
![image](https://user-images.githubusercontent.com/15104768/193406124-aa713b6e-9079-47bf-934b-8345e624e4c1.png)

**Comment by Nadezhda-n** [comment]
![image](https://user-images.githubusercontent.com/99179773/214788121-1659236d-b5b9-4dba-a9a3-d35542aef6dd.png)
ok?

**Comment by rusefillc** [comment]
Perfect @Nadezhda-n
