### ISSUE TITLE
Mechanical improvements for MAP sensor footprint considering SD card on back

### ISSUE THREAD

**Issue by rusefillc** [rusefi/alphax-4chan#66]
We have some boards with MAP pulled off

only three of eight pads are actually used for anything

what tricks like vias and more metal can we try to increases our mechanical chances?

**Comment by rusefillc** [comment]
@ElDominio any chance to see photos of damanges PCBs?

**Comment by rusefillc** [comment]
@andreika-git please check datasheet if we can GND or else currently disconnected pads

**Comment by ElDominio** [comment]
Will upload later today i think they're in my bag

**Comment by ElDominio** [comment]
![IMG_20221006_230709.jpg](https://user-images.githubusercontent.com/5685108/194461662-3bc14145-66d7-4655-b180-ab59cff33dc1.jpg)

**Comment by rusefillc** [comment]
Hot glue did not help these do not even survive shipping :(

![WhatsApp Image 2022-11-29 at 01 10 18](https://user-images.githubusercontent.com/48498823/204452617-de2d17f3-c689-4dee-8171-76c1ed657517.jpg)

@timbelom part of the problem is poor soldering?

![WhatsApp Image 2022-11-29 at 01 12 24](https://user-images.githubusercontent.com/48498823/204452771-7b6756c3-0db8-4d11-8467-36321d648008.jpg)

**Comment by mck1117** [comment]
is that broken solder joints, or pads torn off the board?

**Comment by dron0gus** [comment]
Do not put high profile SMD components close to board edges.

**Comment by rusefillc** [comment]
> Do not put high profile SMD components close to board edges.

plz remind why :)

**Comment by mck1117** [comment]
> plz remind why :)

I seem to remember somebody recently had issues with tall components near the edge recently 🤔

![](https://user-images.githubusercontent.com/48498823/204452771-7b6756c3-0db8-4d11-8467-36321d648008.jpg)

**Comment by ElDominio** [comment]
I assume that having it near the edge means it won't be inside the profile created by the connector and the edges of the board

**Comment by rusefillc** [comment]
@Nadezhda-n please match latest 2chan maybe with larger center hole

**Comment by Nadezhda-n** [comment]
![image](https://user-images.githubusercontent.com/99179773/214780212-e001d9ed-bb42-4962-ad24-ce2e1e470118.png)
Micro_SD_Card on the bottom. 
I guess it needs to be moved?

**Comment by rusefillc** [comment]
Ohhh let's do nothing for now that would be safest?

**Comment by Nadezhda-n** [comment]
https://github.com/rusefi/alphax-4chan/tree/New_rev include this

**Comment by ElDominio** [comment]
> Ohhh let's do nothing for now that would be safest?

Will MAP sensors still bruise easily?

**Comment by rusefillc** [comment]
> Ohhh let's do nothing for now that would be safest?

@Nadezhda-n can we apply the copper change (connected NC pads and vias) but not the huge whole? i.e. can we only make progress which does not require SD card to be moved?

**Comment by rusefillc** [comment]
2chan has another improvement and via to reinforce pads

![image](https://user-images.githubusercontent.com/48498823/215472728-f7421698-de73-4b74-ace6-1fba1ec3d534.png)

**Comment by Nadezhda-n** [comment]
![image](https://user-images.githubusercontent.com/99179773/215820030-b1939f5c-3fad-416d-8772-11dfd9a813ea.png)
