### ISSUE TITLE
CKP pad forever grounded

### ISSUE THREAD

**Issue by ElDominio** [rusefi/alphax-4chan#67]
This photo is probing CKP pin directly

![IMG_20221007_202411.jpg](https://user-images.githubusercontent.com/5685108/194678233-f508351e-5189-4054-a58a-199e4807243c.jpg)

This photo is probing CKP pad
![IMG_20221007_202417.jpg](https://user-images.githubusercontent.com/5685108/194678239-e04e4724-9b4a-413b-bc98-c52dd1e3e672.jpg)

This photo is probing CMP pad
![IMG_20221007_202424.jpg](https://user-images.githubusercontent.com/5685108/194678247-eaafb6ec-fb4f-42ad-8034-f8cdbb2c4c90.jpg)

**Comment by rusefillc** [comment]
@ElDominio please elaborate

which revisions
why do we care
how can I test
what is desired

**Comment by ElDominio** [comment]
This looks like a Lancer, lancer works fine lately except for hall noise but not related to this
