### ISSUE TITLE
VVT target seems to be locked at 25 degrees for intake, settings min/max duty to 0 makes no difference

### ISSUE THREAD

**Issue by ElDominio** [rusefi/alphax-4chan#68]
https://rusefi.com/online/view.php?log=1073

In this log, the VVT solenoid was unplugged and angle was 0. The instant vvt is connected, VVT angle goes to ~25 and nothing I change has any effect, only disconnecting it.

**Comment by ElDominio** [comment]
![image](https://user-images.githubusercontent.com/5685108/194738204-ecc2787a-98a3-44ee-9a54-7f1c70286e36.png)


Oscope looks like this

**Comment by rusefillc** [comment]
@ElDominio what's the status? this looks like firmware issue?

**Comment by ElDominio** [comment]
Actually idk, this ecu is from the Chinese seller and he kept using it in the NOS output.

**Comment by rusefillc** [comment]
@ElDominio what is this ticket about? Please look at it through me eyes.

**Comment by ElDominio** [comment]
This was probably due to bad wiring, closed.
