### ISSUE TITLE
failure to generate ibom

### ISSUE THREAD

**Issue by rusefillc** [rusefi/alphax-4chan#7]
![image](https://user-images.githubusercontent.com/48498823/158457180-b4278c41-4bc6-4f52-b664-1eaea0ba7cef.png)

**Comment by andreika-git** [comment]
https://github.com/rusefi/alphax-4chan/commit/bd28e39ad72888a27bc3180ef14487afb0b1b881
![image](https://user-images.githubusercontent.com/15104768/160268735-a5525483-ae07-43ec-acf5-ca2c3e24f74c.png)
