### ISSUE TITLE
Let's use VND10N06TR-E

### ISSUE THREAD

**Issue by rusefillc** [rusefi/alphax-4chan#70]
JLC has VND10 which is just a bit weaker than VND14 but would give us JLC assembly.

STMicroelectronics VND10N06TR-E
JLCPCB Part #: C2149912

![image](https://user-images.githubusercontent.com/48498823/196511354-d696205e-4738-40ff-85c8-8f0da294563c.png)

**Comment by rusefillc** [comment]
@ElDominio please approve

**Comment by ElDominio** [comment]
approved for all ECUs lol
