### ISSUE TITLE
parts shortage today

### ISSUE THREAD

**Issue by rusefillc** [rusefi/alphax-4chan#71]
Marsel is looking to order a batch of 4chan but BOM shortages

R4,R49 | 4D03WGF1001T5E | R0603-4 | 4D03WGF1001T5E C425239

U103 | AP2331W-7 | SOT-23 | AP2331W-7 C460346

F5,F6 | Fuse-5A-1206 | SMD1206 | S1206-F-5.0A C553924

**Comment by rusefillc** [comment]
@andreika-git can I simply remove U103 from alphax-4chan BOM?

**Comment by rusefillc** [comment]
https://github.com/andreika-git/hellen-one/wiki/JLC-fabrication-component-substitution-options is the relevant page to update

**Comment by rusefillc** [comment]
R0603-4 extended part I know @Qwerty-OFF just wants to replace with four individual 0402?

**Comment by andreika-git** [comment]
> R4,R49 | 4D03WGF1001T5E | R0603-4 | 4D03WGF1001T5E C425239

![image](https://user-images.githubusercontent.com/15104768/198093739-47f224c2-88b4-45ff-9e1e-7be52700b3cd.png)

**Comment by andreika-git** [comment]
> U103 | AP2331W-7 | SOT-23 | AP2331W-7 C460346

AP2331SA-7 C500764

**Comment by andreika-git** [comment]
> F5,F6 | Fuse-5A-1206 | SMD1206 | S1206-F-5.0A C553924

JFC1206-1500FS C136351
