### ISSUE TITLE
rev E U1 missing from iBom?

### ISSUE THREAD

**Issue by ElDominio** [rusefi/alphax-4chan#73]
https://rusefi.com/docs/ibom/alphax_4ch-e-ibom.html

Don't see it on 2chan either, missing from a locally assembled one. What part is this?

**Comment by rusefillc** [comment]
We have a bunch all seem to be caused by same thing https://github.com/andreika-git/hellen-one/issues/191

**Comment by rusefillc** [comment]
@ElDominio is this taken care of?

**Comment by ElDominio** [comment]
If i write U1 on iBom, nothing shows. Is this expected?

**Comment by rusefillc** [comment]
> If i write U1 on iBom, nothing shows. Is this expected?

this seems better on rev F https://rusefi.com/docs/ibom/alphax_4ch-f-ibom.html

**Comment by rusefillc** [comment]
Just realized that we had two separate issues here.

2chan not having part assembled could be very different from 4chan anything
