### ISSUE TITLE
Time to remove jumpers

### ISSUE THREAD

**Issue by rusefillc** [rusefi/alphax-4chan#76]
@ElDominio have you ever used any of the jumpers for any reason? can we remove all or replace with test vias if we ever need space on this PCB? if we want to make the PCB simpler?

**Comment by ElDominio** [comment]
I didn't know what jumpers?? It has jumpers? Where?

Crank/Cam logic analyzer should be vias and not pads. Little holes i can solder pins to if necessary

**Comment by rusefillc** [comment]
@ElDominio these jumpers between connectors and components

![image](https://user-images.githubusercontent.com/48498823/202934258-66562261-9c54-4bce-a221-6be0dcde7848.png)

**Comment by ElDominio** [comment]
fine to remove

**Comment by rusefillc** [comment]
Some were removed to address mounting point issue. Technically theoretically sometimes having at least a via help, having complete jumper might help even more.

We can always remove individual ones if that helps with tracing or else. Replacing with a via keeps at least of some over-engineering.

**Comment by rusefillc** [comment]
Actually closing to keep things simper
