### ISSUE TITLE
Can we change to USB-C connectors on board?

### ISSUE THREAD

**Issue by ElDominio** [rusefi/alphax-4chan#78]
Change USB connector to C2764612 , USB-C type since I have too many USB-C cables laying around

**Comment by rusefillc** [comment]
https://jlcpcb.com/partdetail/XkbConnectivity-U262_061N4BVC11/C2764612

**Comment by Qwerty-OFF** [comment]
https://github.com/rusefi/alphax-2chan/issues/68#issuecomment-1336463362

**Comment by ElDominio** [comment]
https://jlcpcb.com/partdetail/Dealon-USB_TYPE_C018/C2927038

This is compatible?

**Comment by rusefillc** [comment]
@Qwerty-OFF do you see proper connectors at JLC?

@ElDominio do you want USB-C to
* pay
* wait an extra 1 to more weeks
For global sourcing not jlc library?

**Comment by mck1117** [comment]
> https://jlcpcb.com/partdetail/Dealon-USB_TYPE_C018/C2927038
> 
> This is compatible?

be careful with the design rules limits on that, the pins are very small

**Comment by Qwerty-OFF** [comment]
![image](https://user-images.githubusercontent.com/4116383/225440924-eaad6cfb-5d50-439e-a451-662f4f12bae6.png)

**Comment by rusefillc** [comment]
Wow funny timing

![WhatsApp Image 2023-03-15 at 22 26 20](https://user-images.githubusercontent.com/48498823/225494153-a4602287-abcc-4bb7-aa1b-5cf189055500.jpg)
