### ISSUE TITLE
Test points for trigger logic analyzer

### ISSUE THREAD

**Issue by mck1117** [rusefi/alphax-4chan#81]
Add test points for 0.1" headers to more easily probe cam/crank inputs (digital and VR).

**Comment by rusefillc** [comment]
@mck1117 do you mean that SMD pads are not user friendly? i.e. "more easily" than what?

**Comment by rusefillc** [comment]
vias should be possible once 4chan migrates to megamodule

**Comment by mck1117** [comment]
> @mck1117 do you mean that SMD pads are not user friendly? i.e. "more easily" than what?

SMD pads require soldering or a human holding something on there. Most logic analyzers use 0.1" header pin wires, so adding some 0.1" holes to solder a header would optimize scenario of install/remove logic analyzer.

**Comment by rusefillc** [comment]
https://github.com/rusefi/alphax-4chan/issues/87 would kind of help
