### ISSUE TITLE
Remove some of jumpers since two mounting points are grounding stuff

### ISSUE THREAD

**Issue by rusefillc** [rusefi/alphax-4chan#82]
![WhatsApp Image 2022-12-15 at 10 55 36](https://user-images.githubusercontent.com/48498823/207907911-d9f300c2-1f59-48bb-8cd9-7a28f53eee9e.jpg)

![WhatsApp Image 2022-12-15 at 10 55 55](https://user-images.githubusercontent.com/48498823/207907939-5c67129b-c04b-43ab-9fd5-b4001abc84b4.jpg)

**Comment by rusefillc** [comment]
@ElDominio how come this is not an issue for you?

https://www.instagram.com/marsel_zx/ reports actual injector short

**Comment by rusefillc** [comment]
i suggest removing the jumpers which are causing the issue and adding proper bolt mounting points

**Comment by ElDominio** [comment]
Because i tape the bottom of the case because this happened on the old 4chans lol

**Comment by rusefillc** [comment]
![WhatsApp Image 2022-12-15 at 11 10 21](https://user-images.githubusercontent.com/48498823/207922640-171ce089-7ee4-4e07-a469-ab37f0cfedcf.jpg)

**Comment by Nadezhda-n** [comment]
**_some_** 
are there sizes?

**Comment by rusefillc** [comment]
@Nadezhda-n let's remove 7 left and 7 right to behind with, sizes on Sunday

**Comment by Nadezhda-n** [comment]
> @Nadezhda-n let's remove 7 left and 7 right to behind with, sizes on Sunday

wait for sunday

**Comment by Nadezhda-n** [comment]
@rusefillc

**Comment by rusefillc** [comment]
диаметр d=6.2mm
расстояние между центрами примернр 86.7мм

мы там не делаем крепёжных отверстий - просто делаем гладкую плату без голой меди

**Comment by Nadezhda-n** [comment]
> диаметр d=6.2mm расстояние между центрами примернр 86.7мм
> 
> мы там не делаем крепёжных отверстий - просто делаем гладкую плату без голой меди

а высота какая?
Плата ровно по центру корпуса?

**Comment by rusefillc** [comment]
По центру
