### ISSUE TITLE
Disable pull-up on CKP/CMP while staying in Hall mode

### ISSUE THREAD

**Issue by ElDominio** [rusefi/alphax-4chan#83]
For externally pulled-up hall sensors or using Max9926

For more context, I used a MAX9926 on a car that was having issues with the built-in VR module, and it worked fine for a while. Apparently now it's not pulling to ground properly, leading me to believe that disabling the 5V pullup will make the 9926 work correctly, since the 9926 seems to be outputting the correct signal when not connected to the ECU.

**Comment by mck1117** [comment]
Set the pullup mode to VR. Controlling the pullup is the only thing it does.

**Comment by ElDominio** [comment]
Does it not make it "look" at the VR Threshold?

**Comment by mck1117** [comment]
nope, the VR input is separate to the MCU, so it doesn't matter what the VR conditioner circuit is doing.

**Comment by mck1117** [comment]
nope, the digital input circuit is separate.

**Comment by ElDominio** [comment]
Thank you for the clarification!
