### ISSUE TITLE
Exact same tune on RevC and RevE, RevC runs engine, RevE does not

### ISSUE THREAD

**Issue by ElDominio** [rusefi/alphax-4chan#84]
https://rusefi.com/online/view.php?msq=1349

I tried this tune on both a RevC and a RevE and RevC reads RPM and start, while RevE throws a trigger error. I only have a log of RevE so I'll grab one of RevC on sunday, but still odd

**Comment by rusefillc** [comment]
@ElDominio shall we close since it's a pain to reproduce?
