### ISSUE TITLE
rev F: Migrate to vr 0.4

### ISSUE THREAD

**Issue by rusefillc** [rusefi/alphax-4chan#85]
We shall migrate to https://github.com/andreika-git/hellen-one/issues/247

**Comment by Nadezhda-n** [comment]
?

**Comment by rusefillc** [comment]
@ElDominio did this change accomplish anything?

**Comment by rusefillc** [comment]
Looks like impossible to test, will reopen if we ever have VR issues

**Comment by ElDominio** [comment]
@mck1117 saw a bunch of logs of a revF 4chan and said it was much better?
