### ISSUE TITLE
Use mm 0.3+ this is supposed to include improved digital input hardware due to MM

### ISSUE THREAD

**Issue by rusefillc** [rusefi/alphax-4chan#87]
See also https://github.com/rusefi/alphax-8chan/issues/54

**Comment by rusefillc** [comment]
says 
![image](https://user-images.githubusercontent.com/48498823/225475215-c2e953ca-31bb-462d-80dd-ab1786c012c8.png)
right now

**Comment by Qwerty-OFF** [comment]
![image](https://user-images.githubusercontent.com/4116383/226142194-71812ce9-8108-4b55-a2e1-397e2555af5a.png)
