### ISSUE TITLE
update to latest power module

### ISSUE THREAD

**Issue by rusefillc** [rusefi/alphax-4chan#89]
update power module alongside #87?

**Comment by Nadezhda-n** [comment]
Module-power12-0.2 and Module-power5-0.2 -> power_12and5V? 
It isn't trivial, but I can
![image](https://user-images.githubusercontent.com/99179773/215411227-074e9e62-ef8c-478a-92d9-45c2e3c5935a.png)
![image](https://user-images.githubusercontent.com/99179773/215411261-786e3a62-c1bb-433b-acb0-7fe6925d8b22.png)

**Comment by rusefillc** [comment]
Depends on https://github.com/rusefi/alphax-4chan/issues/87

**Comment by Qwerty-OFF** [comment]
![image](https://user-images.githubusercontent.com/4116383/225441852-bf3cfd08-fadf-471c-8386-3931410a4ea0.png)
