### ISSUE TITLE
manual assembly C6

### ISSUE THREAD

**Issue by rusefillc** [rusefi/alphax-4chan#9]
![image](https://user-images.githubusercontent.com/48498823/160286112-4d340ebf-27b0-4403-adf1-50e99711602d.png)

C6 looks to be in the way of manual assembly / solder wig ETB clean-up. Will report once try in real life :)

**Comment by rusefillc** [comment]
not horrible but a bit in the way for sure

are there any options or not really?

**Comment by andreika-git** [comment]
1) The first option is to remove C6, then solder the big chip, and then solder C6 back.
2) The second option is: we move C6 away from the chip in the next rev.

**Comment by rusefillc** [comment]
option 2 please? :)

**Comment by andreika-git** [comment]
Done!
![image](https://user-images.githubusercontent.com/15104768/161111714-1a3cabe3-a918-4f90-b3f0-de3cc1b39a33.png)
