### ISSUE TITLE
Aux connector

### ISSUE THREAD

**Issue by rusefillc** [rusefi/alphax-4chan#90]
(edited)
-> 10 pin Molex microfit internal with additional I/O 
![image](https://user-images.githubusercontent.com/5685108/224511408-4ac6d81d-3283-4bab-84d0-81e2d22ac3aa.png)

things on the molex:
- 2x injector
- 2x ignition (for 6cyl sequential)
- 4x analog in
- 2x 12v 1A high side controllable output

**Comment by ElDominio** [comment]
12v controllable means

When i activate in firmware, produces 12v on the pin, not gnd

**Comment by rusefillc** [comment]
@Qwerty-OFF @ElDominio should we be freaking out with SMD connector like on the picture? shall we go through-hole for mechanical safety?

**Comment by ElDominio** [comment]
I'd say SMD is ok? If users rip it off means bad wiring, I would think

**Comment by mck1117** [comment]
if you have the option, why would you ever use SMD for a user-interfacing connector? That's asking for warranty claims, man.

**Comment by rusefillc** [comment]
@Qwerty-OFF we voted through-hole.

**Comment by ElDominio** [comment]
I know very little about hardware which is why i used question marks. If THT is better, use THT

**Comment by rusefillc** [comment]
Same ignition as on #96 but two more injection channels for aux connector

**Comment by Qwerty-OFF** [comment]
![image](https://user-images.githubusercontent.com/4116383/226148713-d184777b-f0aa-49d6-bd74-e36a9e2a5293.png)
