### ISSUE TITLE
jlc preview corner mess

### ISSUE THREAD

**Issue by rusefillc** [rusefi/alphax-4chan#91]
![image](https://user-images.githubusercontent.com/48498823/215856772-55dcc5ab-25ff-4e07-98a7-886d7aa888b8.png)

**Comment by Nadezhda-n** [comment]
![image](https://user-images.githubusercontent.com/99179773/215860017-f40cd8b1-6f19-47bd-8310-88727a6175cf.png)
![image](https://user-images.githubusercontent.com/99179773/215860490-56e2d955-0b16-4fa4-9150-691ccef7a695.png)
![image](https://user-images.githubusercontent.com/99179773/215860532-6b7218a5-800e-4307-b524-5abdbe5900f4.png)
jls говорит, что там отверстия

**Comment by rusefillc** [comment]
closing for now
