### ISSUE TITLE
Components are missing from alphax_4ch-f-components.png

### ISSUE THREAD

**Issue by rusefillc** [rusefi/alphax-4chan#92]
https://github.com/rusefi/alphax-4chan/blob/main/boards/alphax_4ch-f/board/misc/alphax_4ch-f-components.png does not have many components 

rev E was better

is that a red flag of something broken somewhere on 4chan?

**Comment by andreika-git** [comment]
It seems that gerber/alphax_4ch.wrl was exported incorrectly (the reason is unknown) - it didn't have most of the frame components... When I export it myself from the current alphax_4ch.kicad_pcb, the problem seems to be solved.

**Comment by rusefillc** [comment]
@Qwerty-OFF @Nadezhda-n just FYI

let me close this one I guess, no need to re-generate anything version 'F' does not look critical
