### ISSUE TITLE
JLS parts

### ISSUE THREAD

**Issue by Nadezhda-n** [rusefi/alphax-4chan#93]
**Inventory shortage**:
1. U752 etc 74AHC1G02 (SOT23-5)
2. nSMD005 (PAD-1206-PAD)
~3. U103 AP2331W-7 (SOT-23)~
~4. VND14NV04TR-E (DPAK)~

**No part selected**:
1. JDY-33
2. 33311-24AW-2

**Comment by rusefillc** [comment]
@Qwerty-OFF how about C70064?

**Comment by Qwerty-OFF** [comment]
1. C163710
2. C70064

1. @rusefillc блютуз паяется руками?
2. Основной разъем видимо тоже

**Comment by rusefillc** [comment]
![image](https://user-images.githubusercontent.com/48498823/216366262-0efe8c9a-1567-4917-a9d8-5de17f42c0b8.png)

**Comment by rusefillc** [comment]
![image](https://user-images.githubusercontent.com/48498823/216367104-4e85ddc7-25f7-4163-9a70-ded89da22cb1.png)
