### ISSUE TITLE
5 and 6 cyl on main connector trick

### ISSUE THREAD

**Issue by rusefillc** [rusefi/alphax-4chan#96]
https://github.com/rusefi/alphax-4chan/issues/90 would allow 6 cylinder using aux connector
* we need through hole vias on aux 2x ignition traces to allow jumper wires
* (no action needed) let's make sure to keep at least some jumpers on less important pins like D4 FLEX knock opposite of https://github.com/rusefi/alphax-4chan/issues/76

This would allow 6 cylinder on main connectors with board mod.
* injectors 5 and 6 could be made from existing low sides by just removing diode

**Comment by ElDominio** [comment]
Which existing GPIO could be used for injection?
if it could be any, like IDLE/IDLE2/NOS/VVT/VVT2, then I agree with what you said. My mind is on doing a 6x6 ETB engine with no VVT so losing VVT control loses me nothing

**Comment by Qwerty-OFF** [comment]
IGN5-6 vias for ignition
IGN7-8 for VVT1-2 or INJ5-6 (need to remove D53, D54)
![image](https://user-images.githubusercontent.com/4116383/226141473-0f07b1cf-5da1-40eb-8d49-37fe67963eab.png)

**Comment by ElDominio** [comment]
Can this be done on older boards?

**Comment by rusefillc** [comment]
> Can this be done on older boards?

probably no access to those MCU pads
